/* Generated by Tessent Shell 2022.4 at Mon Apr 28 14:46:44 IST 2025 */
module memlibc_memory_bist_assembly(BIST_CLK, m1_A, m1_WEB, m1_CSB, m1_I, m1_O);
  input  [31:0] m1_I;
  input  [5:0] m1_A;
  input  BIST_CLK, m1_WEB, m1_CSB;
  output [31:0] m1_O;

  memlibc_memory_bist_assembly_mem_container mem_container_inst(
      .m1_A(m1_A), .BIST_CLK(BIST_CLK), .m1_WEB(m1_WEB), .m1_CSB(m1_CSB), .m1_I(m1_I), 
      .m1_mem_inst_O(m1_O)
  );
endmodule

module memlibc_memory_bist_assembly_mem_container(m1_A, BIST_CLK, m1_WEB, m1_CSB, 
                                                  m1_I, m1_mem_inst_O);
  input  [31:0] m1_I;
  input  [5:0] m1_A;
  input  BIST_CLK, m1_WEB, m1_CSB;
  output [31:0] m1_mem_inst_O;

  SPRAM_64x32 m1_mem_inst(
      .A(m1_A), .CE(BIST_CLK), .WEB(m1_WEB), .OEB(1'b0), .CSB(m1_CSB), .I(m1_I), 
      .O(m1_mem_inst_O)
  );
endmodule

