
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  2 2025 16:48:33 IST (May  2 2025 11:18:33 UTC)

// Verification Directory fv/sram_sp_16384d_36w_16m_8b 

module sram_sp_16384d_36w_16m_8b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [13:0] A;
  input [35:0] D, WEN;
  output [35:0] Q;
  wire CLK, CEN, GWEN;
  wire [13:0] A;
  wire [35:0] D, WEN;
  wire [35:0] Q;
  wire [7:0] bank_we;
  wire [35:0] \bank_out[0] ;
  wire [7:0] bank_select;
  wire [35:0] \bank_out[1] ;
  wire [35:0] \bank_out[2] ;
  wire [35:0] \bank_out[3] ;
  wire [35:0] \bank_out[4] ;
  wire [35:0] \bank_out[5] ;
  wire [35:0] \bank_out[6] ;
  wire [35:0] \bank_out[7] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_161, n_238;
  SPRAM_2048x36 \MEM_BANKS[0].bank (.CE (n_238), .OEB (1'b0), .CSB
       (n_161), .WEB (bank_we[0]), .A (A[10:0]), .I (D), .O
       (\bank_out[0] ));
  SPRAM_2048x36 \MEM_BANKS[1].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[1]), .WEB (bank_we[1]), .A (A[10:0]), .I (D), .O
       (\bank_out[1] ));
  SPRAM_2048x36 \MEM_BANKS[2].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[2]), .WEB (bank_we[2]), .A (A[10:0]), .I (D), .O
       (\bank_out[2] ));
  SPRAM_2048x36 \MEM_BANKS[3].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[3]), .WEB (bank_we[3]), .A (A[10:0]), .I (D), .O
       (\bank_out[3] ));
  SPRAM_2048x36 \MEM_BANKS[4].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[4]), .WEB (bank_we[4]), .A (A[10:0]), .I (D), .O
       (\bank_out[4] ));
  SPRAM_2048x36 \MEM_BANKS[5].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[5]), .WEB (bank_we[5]), .A (A[10:0]), .I (D), .O
       (\bank_out[5] ));
  SPRAM_2048x36 \MEM_BANKS[6].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[6]), .WEB (bank_we[6]), .A (A[10:0]), .I (D), .O
       (\bank_out[6] ));
  SPRAM_2048x36 \MEM_BANKS[7].bank (.CE (n_238), .OEB (1'b0), .CSB
       (bank_select[7]), .WEB (bank_we[7]), .A (A[10:0]), .I (D), .O
       (\bank_out[7] ));
  INVX1 g1628(.A (CEN), .Y (n_238));
  NAND4XL g7096__2398(.A (n_129), .B (n_127), .C (n_121), .D (n_123),
       .Y (Q[23]));
  NAND4XL g7097__5107(.A (n_112), .B (n_71), .C (n_32), .D (n_37), .Y
       (Q[34]));
  NAND4XL g7098__6260(.A (n_150), .B (n_134), .C (n_109), .D (n_119),
       .Y (Q[33]));
  NAND4XL g7099__4319(.A (n_148), .B (n_142), .C (n_125), .D (n_132),
       .Y (Q[30]));
  NAND4XL g7100__8428(.A (n_154), .B (n_151), .C (n_147), .D (n_149),
       .Y (Q[13]));
  NAND4XL g7101__5526(.A (n_146), .B (n_143), .C (n_136), .D (n_138),
       .Y (Q[24]));
  NAND4XL g7102__6783(.A (n_145), .B (n_144), .C (n_140), .D (n_141),
       .Y (Q[12]));
  NAND4XL g7103__3680(.A (n_137), .B (n_135), .C (n_131), .D (n_133),
       .Y (Q[11]));
  NAND4XL g7104__1617(.A (n_115), .B (n_106), .C (n_96), .D (n_99), .Y
       (Q[29]));
  NAND4XL g7105__2802(.A (n_139), .B (n_117), .C (n_153), .D (n_58), .Y
       (Q[35]));
  NAND4XL g7106__1705(.A (n_130), .B (n_128), .C (n_124), .D (n_126),
       .Y (Q[10]));
  NAND4XL g7107__5122(.A (n_114), .B (n_110), .C (n_102), .D (n_105),
       .Y (Q[22]));
  NAND4XL g7108__8246(.A (n_122), .B (n_120), .C (n_116), .D (n_118),
       .Y (Q[9]));
  NAND4XL g7109__7098(.A (n_83), .B (n_76), .C (n_47), .D (n_55), .Y
       (Q[32]));
  NAND4XL g7110__6131(.A (n_98), .B (n_94), .C (n_89), .D (n_91), .Y
       (Q[21]));
  NAND4XL g7111__1881(.A (n_113), .B (n_111), .C (n_107), .D (n_108),
       .Y (Q[8]));
  NAND4XL g7112__5115(.A (n_104), .B (n_103), .C (n_100), .D (n_101),
       .Y (Q[7]));
  NAND4XL g7113__7482(.A (n_97), .B (n_95), .C (n_92), .D (n_93), .Y
       (Q[6]));
  NAND4XL g7114__4733(.A (n_51), .B (n_48), .C (n_42), .D (n_43), .Y
       (Q[18]));
  NAND4XL g7115__6161(.A (n_84), .B (n_80), .C (n_73), .D (n_75), .Y
       (Q[20]));
  NAND4XL g7116__9315(.A (n_90), .B (n_159), .C (n_85), .D (n_86), .Y
       (Q[5]));
  NAND4XL g7117__9945(.A (n_82), .B (n_81), .C (n_77), .D (n_78), .Y
       (Q[4]));
  NAND4XL g7118__2883(.A (n_74), .B (n_72), .C (n_68), .D (n_70), .Y
       (Q[3]));
  NAND4XL g7119__2346(.A (n_29), .B (n_26), .C (n_156), .D (n_19), .Y
       (Q[31]));
  NAND4XL g7120__1666(.A (n_53), .B (n_44), .C (n_39), .D (n_41), .Y
       (Q[27]));
  NAND4XL g7121__7410(.A (n_67), .B (n_63), .C (n_57), .D (n_60), .Y
       (Q[19]));
  NAND4XL g7122__6417(.A (n_66), .B (n_64), .C (n_61), .D (n_62), .Y
       (Q[2]));
  NAND4XL g7123__5477(.A (n_16), .B (n_79), .C (n_65), .D (n_69), .Y
       (Q[28]));
  NAND4XL g7124__2398(.A (n_59), .B (n_56), .C (n_52), .D (n_54), .Y
       (Q[1]));
  NAND4XL g7125__5107(.A (n_50), .B (n_49), .C (n_45), .D (n_46), .Y
       (Q[0]));
  NAND4XL g7126__6260(.A (n_40), .B (n_38), .C (n_34), .D (n_36), .Y
       (Q[17]));
  NAND4XL g7127__4319(.A (n_35), .B (n_30), .C (n_24), .D (n_25), .Y
       (Q[26]));
  NAND4XL g7128__8428(.A (n_33), .B (n_31), .C (n_27), .D (n_28), .Y
       (Q[16]));
  NAND4XL g7129__5526(.A (n_23), .B (n_22), .C (n_20), .D (n_21), .Y
       (Q[15]));
  NAND4XL g7130__6783(.A (n_18), .B (n_88), .C (n_152), .D (n_155), .Y
       (Q[25]));
  NAND4XL g7131__3680(.A (n_17), .B (n_87), .C (n_157), .D (n_158), .Y
       (Q[14]));
  AOI22XL g7132__1617(.A0 (\bank_out[2] [5]), .A1 (n_13), .B0
       (\bank_out[3] [5]), .B1 (n_11), .Y (n_159));
  AOI22XL g7133__2802(.A0 (\bank_out[6] [14]), .A1 (n_2), .B0
       (\bank_out[7] [14]), .B1 (n_1), .Y (n_158));
  AOI22XL g7134__1705(.A0 (\bank_out[2] [14]), .A1 (n_13), .B0
       (\bank_out[3] [14]), .B1 (n_11), .Y (n_157));
  AOI22XL g7135__5122(.A0 (\bank_out[2] [31]), .A1 (n_13), .B0
       (\bank_out[3] [31]), .B1 (n_11), .Y (n_156));
  AOI22XL g7136__8246(.A0 (\bank_out[4] [25]), .A1 (n_14), .B0
       (\bank_out[5] [25]), .B1 (n_15), .Y (n_155));
  AOI22XL g7137__7098(.A0 (\bank_out[2] [13]), .A1 (n_13), .B0
       (\bank_out[3] [13]), .B1 (n_11), .Y (n_154));
  AOI22XL g7138__6131(.A0 (\bank_out[0] [35]), .A1 (n_10), .B0
       (\bank_out[1] [35]), .B1 (n_12), .Y (n_153));
  AOI22XL g7139__1881(.A0 (\bank_out[2] [25]), .A1 (n_13), .B0
       (\bank_out[3] [25]), .B1 (n_11), .Y (n_152));
  AOI22XL g7140__5115(.A0 (\bank_out[6] [13]), .A1 (n_2), .B0
       (\bank_out[7] [13]), .B1 (n_1), .Y (n_151));
  AOI22XL g7141__7482(.A0 (\bank_out[4] [33]), .A1 (n_14), .B0
       (\bank_out[5] [33]), .B1 (n_15), .Y (n_150));
  AOI22XL g7142__4733(.A0 (\bank_out[4] [13]), .A1 (n_14), .B0
       (\bank_out[5] [13]), .B1 (n_15), .Y (n_149));
  AOI22XL g7143__6161(.A0 (\bank_out[4] [30]), .A1 (n_14), .B0
       (\bank_out[5] [30]), .B1 (n_15), .Y (n_148));
  AOI22XL g7144__9315(.A0 (\bank_out[0] [13]), .A1 (n_10), .B0
       (\bank_out[1] [13]), .B1 (n_12), .Y (n_147));
  AOI22XL g7145__9945(.A0 (\bank_out[6] [24]), .A1 (n_2), .B0
       (\bank_out[7] [24]), .B1 (n_1), .Y (n_146));
  AOI22XL g7146__2883(.A0 (\bank_out[6] [12]), .A1 (n_2), .B0
       (\bank_out[7] [12]), .B1 (n_1), .Y (n_145));
  AOI22XL g7147__2346(.A0 (\bank_out[4] [12]), .A1 (n_14), .B0
       (\bank_out[5] [12]), .B1 (n_15), .Y (n_144));
  AOI22XL g7148__1666(.A0 (\bank_out[0] [24]), .A1 (n_10), .B0
       (\bank_out[1] [24]), .B1 (n_12), .Y (n_143));
  AOI22XL g7149__7410(.A0 (\bank_out[6] [30]), .A1 (n_2), .B0
       (\bank_out[7] [30]), .B1 (n_1), .Y (n_142));
  AOI22XL g7150__6417(.A0 (\bank_out[2] [12]), .A1 (n_13), .B0
       (\bank_out[3] [12]), .B1 (n_11), .Y (n_141));
  AOI22XL g7151__5477(.A0 (\bank_out[0] [12]), .A1 (n_10), .B0
       (\bank_out[1] [12]), .B1 (n_12), .Y (n_140));
  AOI22XL g7152__2398(.A0 (\bank_out[6] [35]), .A1 (n_2), .B0
       (\bank_out[7] [35]), .B1 (n_1), .Y (n_139));
  AOI22XL g7153__5107(.A0 (\bank_out[4] [24]), .A1 (n_14), .B0
       (\bank_out[5] [24]), .B1 (n_15), .Y (n_138));
  AOI22XL g7154__6260(.A0 (\bank_out[0] [11]), .A1 (n_10), .B0
       (\bank_out[1] [11]), .B1 (n_12), .Y (n_137));
  AOI22XL g7155__4319(.A0 (\bank_out[2] [24]), .A1 (n_13), .B0
       (\bank_out[3] [24]), .B1 (n_11), .Y (n_136));
  AOI22XL g7156__8428(.A0 (\bank_out[6] [11]), .A1 (n_2), .B0
       (\bank_out[7] [11]), .B1 (n_1), .Y (n_135));
  AOI22XL g7157__5526(.A0 (\bank_out[2] [33]), .A1 (n_13), .B0
       (\bank_out[3] [33]), .B1 (n_11), .Y (n_134));
  AOI22XL g7158__6783(.A0 (\bank_out[4] [11]), .A1 (n_14), .B0
       (\bank_out[5] [11]), .B1 (n_15), .Y (n_133));
  AOI22XL g7159__3680(.A0 (\bank_out[2] [30]), .A1 (n_13), .B0
       (\bank_out[3] [30]), .B1 (n_11), .Y (n_132));
  AOI22XL g7160__1617(.A0 (\bank_out[2] [11]), .A1 (n_13), .B0
       (\bank_out[3] [11]), .B1 (n_11), .Y (n_131));
  AOI22XL g7161__2802(.A0 (\bank_out[6] [10]), .A1 (n_2), .B0
       (\bank_out[7] [10]), .B1 (n_1), .Y (n_130));
  AOI22XL g7162__1705(.A0 (\bank_out[2] [23]), .A1 (n_13), .B0
       (\bank_out[3] [23]), .B1 (n_11), .Y (n_129));
  AOI22XL g7163__5122(.A0 (\bank_out[0] [10]), .A1 (n_10), .B0
       (\bank_out[1] [10]), .B1 (n_12), .Y (n_128));
  AOI22XL g7164__8246(.A0 (\bank_out[4] [23]), .A1 (n_14), .B0
       (\bank_out[5] [23]), .B1 (n_15), .Y (n_127));
  AOI22XL g7165__7098(.A0 (\bank_out[4] [10]), .A1 (n_14), .B0
       (\bank_out[5] [10]), .B1 (n_15), .Y (n_126));
  AOI22XL g7166__6131(.A0 (\bank_out[0] [30]), .A1 (n_10), .B0
       (\bank_out[1] [30]), .B1 (n_12), .Y (n_125));
  AOI22XL g7167__1881(.A0 (\bank_out[2] [10]), .A1 (n_13), .B0
       (\bank_out[3] [10]), .B1 (n_11), .Y (n_124));
  AOI22XL g7168__5115(.A0 (\bank_out[6] [23]), .A1 (n_2), .B0
       (\bank_out[7] [23]), .B1 (n_1), .Y (n_123));
  AOI22XL g7169__7482(.A0 (\bank_out[6] [9]), .A1 (n_2), .B0
       (\bank_out[7] [9]), .B1 (n_1), .Y (n_122));
  AOI22XL g7170__4733(.A0 (\bank_out[0] [23]), .A1 (n_10), .B0
       (\bank_out[1] [23]), .B1 (n_12), .Y (n_121));
  AOI22XL g7171__6161(.A0 (\bank_out[0] [9]), .A1 (n_10), .B0
       (\bank_out[1] [9]), .B1 (n_12), .Y (n_120));
  AOI22XL g7172__9315(.A0 (\bank_out[6] [33]), .A1 (n_2), .B0
       (\bank_out[7] [33]), .B1 (n_1), .Y (n_119));
  AOI22XL g7173__9945(.A0 (\bank_out[4] [9]), .A1 (n_14), .B0
       (\bank_out[5] [9]), .B1 (n_15), .Y (n_118));
  AOI22XL g7174__2883(.A0 (\bank_out[4] [35]), .A1 (n_14), .B0
       (\bank_out[5] [35]), .B1 (n_15), .Y (n_117));
  AOI22XL g7175__2346(.A0 (\bank_out[2] [9]), .A1 (n_13), .B0
       (\bank_out[3] [9]), .B1 (n_11), .Y (n_116));
  AOI22XL g7176__1666(.A0 (\bank_out[2] [29]), .A1 (n_13), .B0
       (\bank_out[3] [29]), .B1 (n_11), .Y (n_115));
  AOI22XL g7177__7410(.A0 (\bank_out[2] [22]), .A1 (n_13), .B0
       (\bank_out[3] [22]), .B1 (n_11), .Y (n_114));
  AOI22XL g7178__6417(.A0 (\bank_out[6] [8]), .A1 (n_2), .B0
       (\bank_out[7] [8]), .B1 (n_1), .Y (n_113));
  AOI22XL g7179__5477(.A0 (\bank_out[2] [34]), .A1 (n_13), .B0
       (\bank_out[3] [34]), .B1 (n_11), .Y (n_112));
  AOI22XL g7180__2398(.A0 (\bank_out[4] [8]), .A1 (n_14), .B0
       (\bank_out[5] [8]), .B1 (n_15), .Y (n_111));
  AOI22XL g7181__5107(.A0 (\bank_out[4] [22]), .A1 (n_14), .B0
       (\bank_out[5] [22]), .B1 (n_15), .Y (n_110));
  AOI22XL g7182__6260(.A0 (\bank_out[0] [33]), .A1 (n_10), .B0
       (\bank_out[1] [33]), .B1 (n_12), .Y (n_109));
  AOI22XL g7183__4319(.A0 (\bank_out[2] [8]), .A1 (n_13), .B0
       (\bank_out[3] [8]), .B1 (n_11), .Y (n_108));
  AOI22XL g7184__8428(.A0 (\bank_out[0] [8]), .A1 (n_10), .B0
       (\bank_out[1] [8]), .B1 (n_12), .Y (n_107));
  AOI22XL g7185__5526(.A0 (\bank_out[6] [29]), .A1 (n_2), .B0
       (\bank_out[7] [29]), .B1 (n_1), .Y (n_106));
  AOI22XL g7186__6783(.A0 (\bank_out[6] [22]), .A1 (n_2), .B0
       (\bank_out[7] [22]), .B1 (n_1), .Y (n_105));
  AOI22XL g7187__3680(.A0 (\bank_out[0] [7]), .A1 (n_10), .B0
       (\bank_out[1] [7]), .B1 (n_12), .Y (n_104));
  AOI22XL g7188__1617(.A0 (\bank_out[6] [7]), .A1 (n_2), .B0
       (\bank_out[7] [7]), .B1 (n_1), .Y (n_103));
  AOI22XL g7189__2802(.A0 (\bank_out[0] [22]), .A1 (n_10), .B0
       (\bank_out[1] [22]), .B1 (n_12), .Y (n_102));
  AOI22XL g7190__1705(.A0 (\bank_out[4] [7]), .A1 (n_14), .B0
       (\bank_out[5] [7]), .B1 (n_15), .Y (n_101));
  AOI22XL g7191__5122(.A0 (\bank_out[2] [7]), .A1 (n_13), .B0
       (\bank_out[3] [7]), .B1 (n_11), .Y (n_100));
  AOI22XL g7192__8246(.A0 (\bank_out[4] [29]), .A1 (n_14), .B0
       (\bank_out[5] [29]), .B1 (n_15), .Y (n_99));
  AOI22XL g7193__7098(.A0 (\bank_out[6] [21]), .A1 (n_2), .B0
       (\bank_out[7] [21]), .B1 (n_1), .Y (n_98));
  AOI22XL g7194__6131(.A0 (\bank_out[4] [6]), .A1 (n_14), .B0
       (\bank_out[5] [6]), .B1 (n_15), .Y (n_97));
  AOI22XL g7195__1881(.A0 (\bank_out[0] [29]), .A1 (n_10), .B0
       (\bank_out[1] [29]), .B1 (n_12), .Y (n_96));
  AOI22XL g7196__5115(.A0 (\bank_out[2] [6]), .A1 (n_13), .B0
       (\bank_out[3] [6]), .B1 (n_11), .Y (n_95));
  AOI22XL g7197__7482(.A0 (\bank_out[2] [21]), .A1 (n_13), .B0
       (\bank_out[3] [21]), .B1 (n_11), .Y (n_94));
  AOI22XL g7198__4733(.A0 (\bank_out[6] [6]), .A1 (n_2), .B0
       (\bank_out[7] [6]), .B1 (n_1), .Y (n_93));
  AOI22XL g7199__6161(.A0 (\bank_out[0] [6]), .A1 (n_10), .B0
       (\bank_out[1] [6]), .B1 (n_12), .Y (n_92));
  AOI22XL g7200__9315(.A0 (\bank_out[4] [21]), .A1 (n_14), .B0
       (\bank_out[5] [21]), .B1 (n_15), .Y (n_91));
  AOI22XL g7201__9945(.A0 (\bank_out[0] [5]), .A1 (n_10), .B0
       (\bank_out[1] [5]), .B1 (n_12), .Y (n_90));
  AOI22XL g7202__2883(.A0 (\bank_out[0] [21]), .A1 (n_10), .B0
       (\bank_out[1] [21]), .B1 (n_12), .Y (n_89));
  AOI22XL g7203__2346(.A0 (\bank_out[6] [25]), .A1 (n_2), .B0
       (\bank_out[7] [25]), .B1 (n_1), .Y (n_88));
  AOI22XL g7204__1666(.A0 (\bank_out[4] [14]), .A1 (n_14), .B0
       (\bank_out[5] [14]), .B1 (n_15), .Y (n_87));
  AOI22XL g7205__7410(.A0 (\bank_out[6] [5]), .A1 (n_2), .B0
       (\bank_out[7] [5]), .B1 (n_1), .Y (n_86));
  AOI22XL g7206__6417(.A0 (\bank_out[4] [5]), .A1 (n_14), .B0
       (\bank_out[5] [5]), .B1 (n_15), .Y (n_85));
  AOI22XL g7207__5477(.A0 (\bank_out[0] [20]), .A1 (n_10), .B0
       (\bank_out[1] [20]), .B1 (n_12), .Y (n_84));
  AOI22XL g7208__2398(.A0 (\bank_out[2] [32]), .A1 (n_13), .B0
       (\bank_out[3] [32]), .B1 (n_11), .Y (n_83));
  AOI22XL g7209__5107(.A0 (\bank_out[2] [4]), .A1 (n_13), .B0
       (\bank_out[3] [4]), .B1 (n_11), .Y (n_82));
  AOI22XL g7210__6260(.A0 (\bank_out[6] [4]), .A1 (n_2), .B0
       (\bank_out[7] [4]), .B1 (n_1), .Y (n_81));
  AOI22XL g7211__4319(.A0 (\bank_out[6] [20]), .A1 (n_2), .B0
       (\bank_out[7] [20]), .B1 (n_1), .Y (n_80));
  AOI22XL g7212__8428(.A0 (\bank_out[4] [28]), .A1 (n_14), .B0
       (\bank_out[5] [28]), .B1 (n_15), .Y (n_79));
  AOI22XL g7213__5526(.A0 (\bank_out[4] [4]), .A1 (n_14), .B0
       (\bank_out[5] [4]), .B1 (n_15), .Y (n_78));
  AOI22XL g7214__6783(.A0 (\bank_out[0] [4]), .A1 (n_10), .B0
       (\bank_out[1] [4]), .B1 (n_12), .Y (n_77));
  AOI22XL g7215__3680(.A0 (\bank_out[6] [32]), .A1 (n_2), .B0
       (\bank_out[7] [32]), .B1 (n_1), .Y (n_76));
  AOI22XL g7216__1617(.A0 (\bank_out[4] [20]), .A1 (n_14), .B0
       (\bank_out[5] [20]), .B1 (n_15), .Y (n_75));
  AOI22XL g7217__2802(.A0 (\bank_out[2] [3]), .A1 (n_13), .B0
       (\bank_out[3] [3]), .B1 (n_11), .Y (n_74));
  AOI22XL g7218__1705(.A0 (\bank_out[2] [20]), .A1 (n_13), .B0
       (\bank_out[3] [20]), .B1 (n_11), .Y (n_73));
  AOI22XL g7219__5122(.A0 (\bank_out[0] [3]), .A1 (n_10), .B0
       (\bank_out[1] [3]), .B1 (n_12), .Y (n_72));
  AOI22XL g7220__8246(.A0 (\bank_out[6] [34]), .A1 (n_2), .B0
       (\bank_out[7] [34]), .B1 (n_1), .Y (n_71));
  AOI22XL g7221__7098(.A0 (\bank_out[6] [3]), .A1 (n_2), .B0
       (\bank_out[7] [3]), .B1 (n_1), .Y (n_70));
  AOI22XL g7222__6131(.A0 (\bank_out[6] [28]), .A1 (n_2), .B0
       (\bank_out[7] [28]), .B1 (n_1), .Y (n_69));
  AOI22XL g7223__1881(.A0 (\bank_out[4] [3]), .A1 (n_14), .B0
       (\bank_out[5] [3]), .B1 (n_15), .Y (n_68));
  AOI22XL g7224__5115(.A0 (\bank_out[6] [19]), .A1 (n_2), .B0
       (\bank_out[7] [19]), .B1 (n_1), .Y (n_67));
  AOI22XL g7225__7482(.A0 (\bank_out[0] [2]), .A1 (n_10), .B0
       (\bank_out[1] [2]), .B1 (n_12), .Y (n_66));
  AOI22XL g7226__4733(.A0 (\bank_out[0] [28]), .A1 (n_10), .B0
       (\bank_out[1] [28]), .B1 (n_12), .Y (n_65));
  AOI22XL g7227__6161(.A0 (\bank_out[2] [2]), .A1 (n_13), .B0
       (\bank_out[3] [2]), .B1 (n_11), .Y (n_64));
  AOI22XL g7228__9315(.A0 (\bank_out[0] [19]), .A1 (n_10), .B0
       (\bank_out[1] [19]), .B1 (n_12), .Y (n_63));
  AOI22XL g7229__9945(.A0 (\bank_out[6] [2]), .A1 (n_2), .B0
       (\bank_out[7] [2]), .B1 (n_1), .Y (n_62));
  AOI22XL g7230__2883(.A0 (\bank_out[4] [2]), .A1 (n_14), .B0
       (\bank_out[5] [2]), .B1 (n_15), .Y (n_61));
  AOI22XL g7231__2346(.A0 (\bank_out[4] [19]), .A1 (n_14), .B0
       (\bank_out[5] [19]), .B1 (n_15), .Y (n_60));
  AOI22XL g7232__1666(.A0 (\bank_out[0] [1]), .A1 (n_10), .B0
       (\bank_out[1] [1]), .B1 (n_12), .Y (n_59));
  AOI22XL g7233__7410(.A0 (\bank_out[2] [35]), .A1 (n_13), .B0
       (\bank_out[3] [35]), .B1 (n_11), .Y (n_58));
  AOI22XL g7234__6417(.A0 (\bank_out[2] [19]), .A1 (n_13), .B0
       (\bank_out[3] [19]), .B1 (n_11), .Y (n_57));
  AOI22XL g7235__5477(.A0 (\bank_out[2] [1]), .A1 (n_13), .B0
       (\bank_out[3] [1]), .B1 (n_11), .Y (n_56));
  AOI22XL g7236__2398(.A0 (\bank_out[4] [32]), .A1 (n_14), .B0
       (\bank_out[5] [32]), .B1 (n_15), .Y (n_55));
  AOI22XL g7237__5107(.A0 (\bank_out[6] [1]), .A1 (n_2), .B0
       (\bank_out[7] [1]), .B1 (n_1), .Y (n_54));
  AOI22XL g7238__6260(.A0 (\bank_out[4] [27]), .A1 (n_14), .B0
       (\bank_out[5] [27]), .B1 (n_15), .Y (n_53));
  AOI22XL g7239__4319(.A0 (\bank_out[4] [1]), .A1 (n_14), .B0
       (\bank_out[5] [1]), .B1 (n_15), .Y (n_52));
  AOI22XL g7240__8428(.A0 (\bank_out[0] [18]), .A1 (n_10), .B0
       (\bank_out[1] [18]), .B1 (n_12), .Y (n_51));
  AOI22XL g7241__5526(.A0 (\bank_out[0] [0]), .A1 (n_10), .B0
       (\bank_out[1] [0]), .B1 (n_12), .Y (n_50));
  AOI22XL g7242__6783(.A0 (\bank_out[4] [0]), .A1 (n_14), .B0
       (\bank_out[5] [0]), .B1 (n_15), .Y (n_49));
  AOI22XL g7243__3680(.A0 (\bank_out[6] [18]), .A1 (n_2), .B0
       (\bank_out[7] [18]), .B1 (n_1), .Y (n_48));
  AOI22XL g7244__1617(.A0 (\bank_out[0] [32]), .A1 (n_10), .B0
       (\bank_out[1] [32]), .B1 (n_12), .Y (n_47));
  AOI22XL g7245__2802(.A0 (\bank_out[6] [0]), .A1 (n_2), .B0
       (\bank_out[7] [0]), .B1 (n_1), .Y (n_46));
  AOI22XL g7246__1705(.A0 (\bank_out[2] [0]), .A1 (n_13), .B0
       (\bank_out[3] [0]), .B1 (n_11), .Y (n_45));
  AOI22XL g7247__5122(.A0 (\bank_out[0] [27]), .A1 (n_10), .B0
       (\bank_out[1] [27]), .B1 (n_12), .Y (n_44));
  AOI22XL g7248__8246(.A0 (\bank_out[4] [18]), .A1 (n_14), .B0
       (\bank_out[5] [18]), .B1 (n_15), .Y (n_43));
  AOI22XL g7249__7098(.A0 (\bank_out[2] [18]), .A1 (n_13), .B0
       (\bank_out[3] [18]), .B1 (n_11), .Y (n_42));
  AOI22XL g7250__6131(.A0 (\bank_out[6] [27]), .A1 (n_2), .B0
       (\bank_out[7] [27]), .B1 (n_1), .Y (n_41));
  AOI22XL g7251__1881(.A0 (\bank_out[6] [17]), .A1 (n_2), .B0
       (\bank_out[7] [17]), .B1 (n_1), .Y (n_40));
  AOI22XL g7252__5115(.A0 (\bank_out[2] [27]), .A1 (n_13), .B0
       (\bank_out[3] [27]), .B1 (n_11), .Y (n_39));
  AOI22XL g7253__7482(.A0 (\bank_out[2] [17]), .A1 (n_13), .B0
       (\bank_out[3] [17]), .B1 (n_11), .Y (n_38));
  AOI22XL g7254__4733(.A0 (\bank_out[4] [34]), .A1 (n_14), .B0
       (\bank_out[5] [34]), .B1 (n_15), .Y (n_37));
  AOI22XL g7255__6161(.A0 (\bank_out[4] [17]), .A1 (n_14), .B0
       (\bank_out[5] [17]), .B1 (n_15), .Y (n_36));
  AOI22XL g7256__9315(.A0 (\bank_out[2] [26]), .A1 (n_13), .B0
       (\bank_out[3] [26]), .B1 (n_11), .Y (n_35));
  AOI22XL g7257__9945(.A0 (\bank_out[0] [17]), .A1 (n_10), .B0
       (\bank_out[1] [17]), .B1 (n_12), .Y (n_34));
  AOI22XL g7258__2883(.A0 (\bank_out[0] [16]), .A1 (n_10), .B0
       (\bank_out[1] [16]), .B1 (n_12), .Y (n_33));
  AOI22XL g7259__2346(.A0 (\bank_out[0] [34]), .A1 (n_10), .B0
       (\bank_out[1] [34]), .B1 (n_12), .Y (n_32));
  AOI22XL g7260__1666(.A0 (\bank_out[4] [16]), .A1 (n_14), .B0
       (\bank_out[5] [16]), .B1 (n_15), .Y (n_31));
  AOI22XL g7261__7410(.A0 (\bank_out[4] [26]), .A1 (n_14), .B0
       (\bank_out[5] [26]), .B1 (n_15), .Y (n_30));
  AOI22XL g7262__6417(.A0 (\bank_out[4] [31]), .A1 (n_14), .B0
       (\bank_out[5] [31]), .B1 (n_15), .Y (n_29));
  AOI22XL g7263__5477(.A0 (\bank_out[6] [16]), .A1 (n_2), .B0
       (\bank_out[7] [16]), .B1 (n_1), .Y (n_28));
  AOI22XL g7264__2398(.A0 (\bank_out[2] [16]), .A1 (n_13), .B0
       (\bank_out[3] [16]), .B1 (n_11), .Y (n_27));
  AOI22XL g7265__5107(.A0 (\bank_out[0] [31]), .A1 (n_10), .B0
       (\bank_out[1] [31]), .B1 (n_12), .Y (n_26));
  AOI22XL g7266__6260(.A0 (\bank_out[6] [26]), .A1 (n_2), .B0
       (\bank_out[7] [26]), .B1 (n_1), .Y (n_25));
  AOI22XL g7267__4319(.A0 (\bank_out[0] [26]), .A1 (n_10), .B0
       (\bank_out[1] [26]), .B1 (n_12), .Y (n_24));
  AOI22XL g7268__8428(.A0 (\bank_out[2] [15]), .A1 (n_13), .B0
       (\bank_out[3] [15]), .B1 (n_11), .Y (n_23));
  AOI22XL g7269__5526(.A0 (\bank_out[4] [15]), .A1 (n_14), .B0
       (\bank_out[5] [15]), .B1 (n_15), .Y (n_22));
  AOI22XL g7270__6783(.A0 (\bank_out[6] [15]), .A1 (n_2), .B0
       (\bank_out[7] [15]), .B1 (n_1), .Y (n_21));
  AOI22XL g7271__3680(.A0 (\bank_out[0] [15]), .A1 (n_10), .B0
       (\bank_out[1] [15]), .B1 (n_12), .Y (n_20));
  AOI22XL g7272__1617(.A0 (\bank_out[6] [31]), .A1 (n_2), .B0
       (\bank_out[7] [31]), .B1 (n_1), .Y (n_19));
  AOI22XL g7273__2802(.A0 (\bank_out[0] [25]), .A1 (n_10), .B0
       (\bank_out[1] [25]), .B1 (n_12), .Y (n_18));
  AOI22XL g7274__1705(.A0 (\bank_out[0] [14]), .A1 (n_10), .B0
       (\bank_out[1] [14]), .B1 (n_12), .Y (n_17));
  AOI22XL g7275__5122(.A0 (\bank_out[2] [28]), .A1 (n_13), .B0
       (\bank_out[3] [28]), .B1 (n_11), .Y (n_16));
  NAND2XL g7276__8246(.A (n_4), .B (n_12), .Y (bank_we[1]));
  NAND2XL g7277__7098(.A (n_4), .B (n_13), .Y (bank_we[2]));
  NAND2XL g7278__6131(.A (n_4), .B (n_11), .Y (bank_we[3]));
  NAND2XL g7279__1881(.A (n_4), .B (n_10), .Y (bank_we[0]));
  NAND2XL g7280__5115(.A (n_4), .B (n_1), .Y (bank_we[7]));
  NAND2XL g7281__7482(.A (n_4), .B (n_15), .Y (bank_we[5]));
  NAND2XL g7282__4733(.A (n_4), .B (n_14), .Y (bank_we[4]));
  NAND2XL g7283__6161(.A (n_4), .B (n_2), .Y (bank_we[6]));
  INVX1 g7284(.A (n_1), .Y (bank_select[7]));
  INVX1 g7285(.A (n_15), .Y (bank_select[5]));
  INVX1 g7286(.A (n_2), .Y (bank_select[6]));
  INVX1 g7287(.A (n_14), .Y (bank_select[4]));
  NOR2X2 g7289__9315(.A (n_0), .B (A[12]), .Y (n_15));
  NOR2X2 g7291__9945(.A (n_8), .B (A[12]), .Y (n_14));
  INVX1 g7292(.A (n_13), .Y (bank_select[2]));
  INVX1 g7293(.A (n_12), .Y (bank_select[1]));
  INVX1 g7294(.A (n_11), .Y (bank_select[3]));
  INVX1 g7295(.A (n_10), .Y (n_161));
  AND2X2 g7296__2883(.A (n_9), .B (A[12]), .Y (n_13));
  AND2X2 g7297__2346(.A (n_7), .B (n_3), .Y (n_12));
  AND2X2 g7298__1666(.A (n_7), .B (A[12]), .Y (n_11));
  AND2X2 g7299__7410(.A (n_9), .B (n_3), .Y (n_10));
  NOR2BXL g7301__6417(.AN (n_5), .B (A[13]), .Y (n_9));
  NAND2XL g7302__5477(.A (A[13]), .B (n_5), .Y (n_8));
  NOR2XL g7305__2398(.A (n_6), .B (A[13]), .Y (n_7));
  NAND2BXL g7307__5107(.AN (CEN), .B (A[11]), .Y (n_6));
  NOR2XL g7308__6260(.A (CEN), .B (A[11]), .Y (n_5));
  INVX1 g7309(.A (GWEN), .Y (n_4));
  INVX1 g7310(.A (A[12]), .Y (n_3));
  NOR2BX2 g2__4319(.AN (A[12]), .B (n_8), .Y (n_2));
  NOR2BX2 g7311__8428(.AN (A[12]), .B (n_0), .Y (n_1));
  NAND2BX1 g7312__5526(.AN (n_6), .B (A[13]), .Y (n_0));
endmodule

