
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  2 2025 15:16:01 IST (May  2 2025 09:46:01 UTC)

// Verification Directory fv/sram_sp_512d_32w_4m_2b 

module sram_sp_512d_32w_4m_2b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [8:0] A;
  input [31:0] D, WEN;
  output [31:0] Q;
  wire CLK, CEN, GWEN;
  wire [8:0] A;
  wire [31:0] D, WEN;
  wire [31:0] Q;
  wire [7:0] bank_we;
  wire [31:0] \bank_out[0] ;
  wire [7:0] bank_select;
  wire [31:0] \bank_out[1] ;
  wire [31:0] \bank_out[2] ;
  wire [31:0] \bank_out[3] ;
  wire [31:0] \bank_out[4] ;
  wire [31:0] \bank_out[5] ;
  wire [31:0] \bank_out[6] ;
  wire [31:0] \bank_out[7] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_145, n_214;
  SPRAM_64x32 \MEM_BANKS[0].bank (.CE (n_214), .OEB (1'b0), .CSB
       (n_145), .WEB (bank_we[0]), .A (A[5:0]), .I (D), .O
       (\bank_out[0] ));
  SPRAM_64x32 \MEM_BANKS[1].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[1]), .WEB (bank_we[1]), .A (A[5:0]), .I (D), .O
       (\bank_out[1] ));
  SPRAM_64x32 \MEM_BANKS[2].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[2]), .WEB (bank_we[2]), .A (A[5:0]), .I (D), .O
       (\bank_out[2] ));
  SPRAM_64x32 \MEM_BANKS[3].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[3]), .WEB (bank_we[3]), .A (A[5:0]), .I (D), .O
       (\bank_out[3] ));
  SPRAM_64x32 \MEM_BANKS[4].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[4]), .WEB (bank_we[4]), .A (A[5:0]), .I (D), .O
       (\bank_out[4] ));
  SPRAM_64x32 \MEM_BANKS[5].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[5]), .WEB (bank_we[5]), .A (A[5:0]), .I (D), .O
       (\bank_out[5] ));
  SPRAM_64x32 \MEM_BANKS[6].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[6]), .WEB (bank_we[6]), .A (A[5:0]), .I (D), .O
       (\bank_out[6] ));
  SPRAM_64x32 \MEM_BANKS[7].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[7]), .WEB (bank_we[7]), .A (A[5:0]), .I (D), .O
       (\bank_out[7] ));
  INVX1 g1480(.A (CEN), .Y (n_214));
  NAND4XL g6351__2398(.A (n_97), .B (n_95), .C (n_91), .D (n_92), .Y
       (Q[4]));
  NAND4XL g6352__5107(.A (n_96), .B (n_53), .C (n_25), .D (n_38), .Y
       (Q[30]));
  NAND4XL g6353__6260(.A (n_134), .B (n_118), .C (n_93), .D (n_103), .Y
       (Q[29]));
  NAND4XL g6354__4319(.A (n_132), .B (n_126), .C (n_109), .D (n_116),
       .Y (Q[26]));
  NAND4XL g6355__8428(.A (n_138), .B (n_135), .C (n_131), .D (n_133),
       .Y (Q[9]));
  NAND4XL g6356__5526(.A (n_130), .B (n_127), .C (n_120), .D (n_122),
       .Y (Q[20]));
  NAND4XL g6357__6783(.A (n_129), .B (n_128), .C (n_124), .D (n_125),
       .Y (Q[8]));
  NAND4XL g6358__3680(.A (n_121), .B (n_119), .C (n_115), .D (n_117),
       .Y (Q[7]));
  NAND4XL g6359__1617(.A (n_99), .B (n_90), .C (n_81), .D (n_83), .Y
       (Q[25]));
  NAND4XL g6360__2802(.A (n_113), .B (n_143), .C (n_105), .D (n_107),
       .Y (Q[19]));
  NAND4XL g6361__1705(.A (n_114), .B (n_112), .C (n_108), .D (n_110),
       .Y (Q[6]));
  NAND4XL g6362__5122(.A (n_98), .B (n_94), .C (n_86), .D (n_89), .Y
       (Q[18]));
  NAND4XL g6363__8246(.A (n_106), .B (n_104), .C (n_100), .D (n_102),
       .Y (Q[5]));
  NAND4XL g6364__7098(.A (n_67), .B (n_60), .C (n_79), .D (n_51), .Y
       (Q[28]));
  NAND4XL g6365__6131(.A (n_82), .B (n_47), .C (n_73), .D (n_75), .Y
       (Q[17]));
  NAND4XL g6366__1881(.A (n_123), .B (n_101), .C (n_137), .D (n_33), .Y
       (Q[31]));
  NAND4XL g6367__5115(.A (n_17), .B (n_16), .C (n_141), .D (n_142), .Y
       (Q[10]));
  NAND4XL g6368__7482(.A (n_77), .B (n_80), .C (n_76), .D (n_78), .Y
       (Q[2]));
  NAND4XL g6369__4733(.A (n_71), .B (n_63), .C (n_55), .D (n_57), .Y
       (Q[24]));
  NAND4XL g6370__6161(.A (n_68), .B (n_64), .C (n_58), .D (n_59), .Y
       (Q[16]));
  NAND4XL g6371__9315(.A (n_74), .B (n_72), .C (n_69), .D (n_70), .Y
       (Q[1]));
  NAND4XL g6372__9945(.A (n_66), .B (n_65), .C (n_61), .D (n_62), .Y
       (Q[0]));
  NAND4XL g6373__2883(.A (n_30), .B (n_27), .C (n_140), .D (n_19), .Y
       (Q[27]));
  NAND4XL g6374__2346(.A (n_49), .B (n_45), .C (n_40), .D (n_42), .Y
       (Q[23]));
  NAND4XL g6375__1666(.A (n_56), .B (n_54), .C (n_50), .D (n_52), .Y
       (Q[15]));
  NAND4XL g6376__7410(.A (n_48), .B (n_46), .C (n_43), .D (n_44), .Y
       (Q[14]));
  NAND4XL g6377__6417(.A (n_41), .B (n_39), .C (n_35), .D (n_37), .Y
       (Q[13]));
  NAND4XL g6378__5477(.A (n_36), .B (n_31), .C (n_22), .D (n_26), .Y
       (Q[22]));
  NAND4XL g6379__2398(.A (n_34), .B (n_32), .C (n_28), .D (n_29), .Y
       (Q[12]));
  NAND4XL g6380__5107(.A (n_24), .B (n_23), .C (n_20), .D (n_21), .Y
       (Q[11]));
  NAND4XL g6381__6260(.A (n_18), .B (n_111), .C (n_136), .D (n_139), .Y
       (Q[21]));
  NAND4XL g6382__4319(.A (n_88), .B (n_87), .C (n_84), .D (n_85), .Y
       (Q[3]));
  AOI22XL g6383__8428(.A0 (\bank_out[6] [19]), .A1 (n_13), .B0
       (\bank_out[7] [19]), .B1 (n_14), .Y (n_143));
  AOI22XL g6384__5526(.A0 (\bank_out[4] [10]), .A1 (n_10), .B0
       (\bank_out[5] [10]), .B1 (n_9), .Y (n_142));
  AOI22XL g6385__6783(.A0 (\bank_out[0] [10]), .A1 (n_11), .B0
       (\bank_out[1] [10]), .B1 (n_12), .Y (n_141));
  AOI22XL g6386__3680(.A0 (\bank_out[2] [27]), .A1 (n_8), .B0
       (\bank_out[3] [27]), .B1 (n_15), .Y (n_140));
  AOI22XL g6387__1617(.A0 (\bank_out[4] [21]), .A1 (n_10), .B0
       (\bank_out[5] [21]), .B1 (n_9), .Y (n_139));
  AOI22XL g6388__2802(.A0 (\bank_out[0] [9]), .A1 (n_11), .B0
       (\bank_out[1] [9]), .B1 (n_12), .Y (n_138));
  AOI22XL g6389__1705(.A0 (\bank_out[0] [31]), .A1 (n_11), .B0
       (\bank_out[1] [31]), .B1 (n_12), .Y (n_137));
  AOI22XL g6390__5122(.A0 (\bank_out[2] [21]), .A1 (n_8), .B0
       (\bank_out[3] [21]), .B1 (n_15), .Y (n_136));
  AOI22XL g6391__8246(.A0 (\bank_out[6] [9]), .A1 (n_13), .B0
       (\bank_out[7] [9]), .B1 (n_14), .Y (n_135));
  AOI22XL g6392__7098(.A0 (\bank_out[6] [29]), .A1 (n_13), .B0
       (\bank_out[7] [29]), .B1 (n_14), .Y (n_134));
  AOI22XL g6393__6131(.A0 (\bank_out[4] [9]), .A1 (n_10), .B0
       (\bank_out[5] [9]), .B1 (n_9), .Y (n_133));
  AOI22XL g6394__1881(.A0 (\bank_out[0] [26]), .A1 (n_11), .B0
       (\bank_out[1] [26]), .B1 (n_12), .Y (n_132));
  AOI22XL g6395__5115(.A0 (\bank_out[2] [9]), .A1 (n_8), .B0
       (\bank_out[3] [9]), .B1 (n_15), .Y (n_131));
  AOI22XL g6396__7482(.A0 (\bank_out[4] [20]), .A1 (n_10), .B0
       (\bank_out[5] [20]), .B1 (n_9), .Y (n_130));
  AOI22XL g6397__4733(.A0 (\bank_out[2] [8]), .A1 (n_8), .B0
       (\bank_out[3] [8]), .B1 (n_15), .Y (n_129));
  AOI22XL g6398__6161(.A0 (\bank_out[0] [8]), .A1 (n_11), .B0
       (\bank_out[1] [8]), .B1 (n_12), .Y (n_128));
  AOI22XL g6399__9315(.A0 (\bank_out[2] [20]), .A1 (n_8), .B0
       (\bank_out[3] [20]), .B1 (n_15), .Y (n_127));
  AOI22XL g6400__9945(.A0 (\bank_out[6] [26]), .A1 (n_13), .B0
       (\bank_out[7] [26]), .B1 (n_14), .Y (n_126));
  AOI22XL g6401__2883(.A0 (\bank_out[6] [8]), .A1 (n_13), .B0
       (\bank_out[7] [8]), .B1 (n_14), .Y (n_125));
  AOI22XL g6402__2346(.A0 (\bank_out[4] [8]), .A1 (n_10), .B0
       (\bank_out[5] [8]), .B1 (n_9), .Y (n_124));
  AOI22XL g6403__1666(.A0 (\bank_out[4] [31]), .A1 (n_10), .B0
       (\bank_out[5] [31]), .B1 (n_9), .Y (n_123));
  AOI22XL g6404__7410(.A0 (\bank_out[6] [20]), .A1 (n_13), .B0
       (\bank_out[7] [20]), .B1 (n_14), .Y (n_122));
  AOI22XL g6405__6417(.A0 (\bank_out[6] [7]), .A1 (n_13), .B0
       (\bank_out[7] [7]), .B1 (n_14), .Y (n_121));
  AOI22XL g6406__5477(.A0 (\bank_out[0] [20]), .A1 (n_11), .B0
       (\bank_out[1] [20]), .B1 (n_12), .Y (n_120));
  AOI22XL g6407__2398(.A0 (\bank_out[2] [7]), .A1 (n_8), .B0
       (\bank_out[3] [7]), .B1 (n_15), .Y (n_119));
  AOI22XL g6408__5107(.A0 (\bank_out[0] [29]), .A1 (n_11), .B0
       (\bank_out[1] [29]), .B1 (n_12), .Y (n_118));
  AOI22XL g6409__6260(.A0 (\bank_out[4] [7]), .A1 (n_10), .B0
       (\bank_out[5] [7]), .B1 (n_9), .Y (n_117));
  AOI22XL g6410__4319(.A0 (\bank_out[4] [26]), .A1 (n_10), .B0
       (\bank_out[5] [26]), .B1 (n_9), .Y (n_116));
  AOI22XL g6411__8428(.A0 (\bank_out[0] [7]), .A1 (n_11), .B0
       (\bank_out[1] [7]), .B1 (n_12), .Y (n_115));
  AOI22XL g6412__5526(.A0 (\bank_out[2] [6]), .A1 (n_8), .B0
       (\bank_out[3] [6]), .B1 (n_15), .Y (n_114));
  AOI22XL g6413__6783(.A0 (\bank_out[2] [19]), .A1 (n_8), .B0
       (\bank_out[3] [19]), .B1 (n_15), .Y (n_113));
  AOI22XL g6414__3680(.A0 (\bank_out[0] [6]), .A1 (n_11), .B0
       (\bank_out[1] [6]), .B1 (n_12), .Y (n_112));
  AOI22XL g6415__1617(.A0 (\bank_out[0] [21]), .A1 (n_11), .B0
       (\bank_out[1] [21]), .B1 (n_12), .Y (n_111));
  AOI22XL g6416__2802(.A0 (\bank_out[6] [6]), .A1 (n_13), .B0
       (\bank_out[7] [6]), .B1 (n_14), .Y (n_110));
  AOI22XL g6417__1705(.A0 (\bank_out[2] [26]), .A1 (n_8), .B0
       (\bank_out[3] [26]), .B1 (n_15), .Y (n_109));
  AOI22XL g6418__5122(.A0 (\bank_out[4] [6]), .A1 (n_10), .B0
       (\bank_out[5] [6]), .B1 (n_9), .Y (n_108));
  AOI22XL g6419__8246(.A0 (\bank_out[4] [19]), .A1 (n_10), .B0
       (\bank_out[5] [19]), .B1 (n_9), .Y (n_107));
  AOI22XL g6420__7098(.A0 (\bank_out[0] [5]), .A1 (n_11), .B0
       (\bank_out[1] [5]), .B1 (n_12), .Y (n_106));
  AOI22XL g6421__6131(.A0 (\bank_out[0] [19]), .A1 (n_11), .B0
       (\bank_out[1] [19]), .B1 (n_12), .Y (n_105));
  AOI22XL g6422__1881(.A0 (\bank_out[6] [5]), .A1 (n_13), .B0
       (\bank_out[7] [5]), .B1 (n_14), .Y (n_104));
  AOI22XL g6423__5115(.A0 (\bank_out[4] [29]), .A1 (n_10), .B0
       (\bank_out[5] [29]), .B1 (n_9), .Y (n_103));
  AOI22XL g6424__7482(.A0 (\bank_out[4] [5]), .A1 (n_10), .B0
       (\bank_out[5] [5]), .B1 (n_9), .Y (n_102));
  AOI22XL g6425__4733(.A0 (\bank_out[2] [31]), .A1 (n_8), .B0
       (\bank_out[3] [31]), .B1 (n_15), .Y (n_101));
  AOI22XL g6426__6161(.A0 (\bank_out[2] [5]), .A1 (n_8), .B0
       (\bank_out[3] [5]), .B1 (n_15), .Y (n_100));
  AOI22XL g6427__9315(.A0 (\bank_out[6] [25]), .A1 (n_13), .B0
       (\bank_out[7] [25]), .B1 (n_14), .Y (n_99));
  AOI22XL g6428__9945(.A0 (\bank_out[6] [18]), .A1 (n_13), .B0
       (\bank_out[7] [18]), .B1 (n_14), .Y (n_98));
  AOI22XL g6429__2883(.A0 (\bank_out[4] [4]), .A1 (n_10), .B0
       (\bank_out[5] [4]), .B1 (n_9), .Y (n_97));
  AOI22XL g6430__2346(.A0 (\bank_out[6] [30]), .A1 (n_13), .B0
       (\bank_out[7] [30]), .B1 (n_14), .Y (n_96));
  AOI22XL g6431__1666(.A0 (\bank_out[0] [4]), .A1 (n_11), .B0
       (\bank_out[1] [4]), .B1 (n_12), .Y (n_95));
  AOI22XL g6432__7410(.A0 (\bank_out[2] [18]), .A1 (n_8), .B0
       (\bank_out[3] [18]), .B1 (n_15), .Y (n_94));
  AOI22XL g6433__6417(.A0 (\bank_out[2] [29]), .A1 (n_8), .B0
       (\bank_out[3] [29]), .B1 (n_15), .Y (n_93));
  AOI22XL g6434__5477(.A0 (\bank_out[6] [4]), .A1 (n_13), .B0
       (\bank_out[7] [4]), .B1 (n_14), .Y (n_92));
  AOI22XL g6435__2398(.A0 (\bank_out[2] [4]), .A1 (n_8), .B0
       (\bank_out[3] [4]), .B1 (n_15), .Y (n_91));
  AOI22XL g6436__5107(.A0 (\bank_out[4] [25]), .A1 (n_10), .B0
       (\bank_out[5] [25]), .B1 (n_9), .Y (n_90));
  AOI22XL g6437__6260(.A0 (\bank_out[4] [18]), .A1 (n_10), .B0
       (\bank_out[5] [18]), .B1 (n_9), .Y (n_89));
  AOI22XL g6438__4319(.A0 (\bank_out[4] [3]), .A1 (n_10), .B0
       (\bank_out[5] [3]), .B1 (n_9), .Y (n_88));
  AOI22XL g6439__8428(.A0 (\bank_out[0] [3]), .A1 (n_11), .B0
       (\bank_out[1] [3]), .B1 (n_12), .Y (n_87));
  AOI22XL g6440__5526(.A0 (\bank_out[0] [18]), .A1 (n_11), .B0
       (\bank_out[1] [18]), .B1 (n_12), .Y (n_86));
  AOI22XL g6441__6783(.A0 (\bank_out[6] [3]), .A1 (n_13), .B0
       (\bank_out[7] [3]), .B1 (n_14), .Y (n_85));
  AOI22XL g6442__3680(.A0 (\bank_out[2] [3]), .A1 (n_8), .B0
       (\bank_out[3] [3]), .B1 (n_15), .Y (n_84));
  AOI22XL g6443__1617(.A0 (\bank_out[2] [25]), .A1 (n_8), .B0
       (\bank_out[3] [25]), .B1 (n_15), .Y (n_83));
  AOI22XL g6444__2802(.A0 (\bank_out[2] [17]), .A1 (n_8), .B0
       (\bank_out[3] [17]), .B1 (n_15), .Y (n_82));
  AOI22XL g6445__1705(.A0 (\bank_out[0] [25]), .A1 (n_11), .B0
       (\bank_out[1] [25]), .B1 (n_12), .Y (n_81));
  AOI22XL g6446__5122(.A0 (\bank_out[0] [2]), .A1 (n_11), .B0
       (\bank_out[1] [2]), .B1 (n_12), .Y (n_80));
  AOI22XL g6447__8246(.A0 (\bank_out[0] [28]), .A1 (n_11), .B0
       (\bank_out[1] [28]), .B1 (n_12), .Y (n_79));
  AOI22XL g6448__7098(.A0 (\bank_out[4] [2]), .A1 (n_10), .B0
       (\bank_out[5] [2]), .B1 (n_9), .Y (n_78));
  AOI22XL g6449__6131(.A0 (\bank_out[6] [2]), .A1 (n_13), .B0
       (\bank_out[7] [2]), .B1 (n_14), .Y (n_77));
  AOI22XL g6450__1881(.A0 (\bank_out[2] [2]), .A1 (n_8), .B0
       (\bank_out[3] [2]), .B1 (n_15), .Y (n_76));
  AOI22XL g6451__5115(.A0 (\bank_out[6] [17]), .A1 (n_13), .B0
       (\bank_out[7] [17]), .B1 (n_14), .Y (n_75));
  AOI22XL g6452__7482(.A0 (\bank_out[2] [1]), .A1 (n_8), .B0
       (\bank_out[3] [1]), .B1 (n_15), .Y (n_74));
  AOI22XL g6453__4733(.A0 (\bank_out[4] [17]), .A1 (n_10), .B0
       (\bank_out[5] [17]), .B1 (n_9), .Y (n_73));
  AOI22XL g6454__6161(.A0 (\bank_out[6] [1]), .A1 (n_13), .B0
       (\bank_out[7] [1]), .B1 (n_14), .Y (n_72));
  AOI22XL g6455__9315(.A0 (\bank_out[4] [24]), .A1 (n_10), .B0
       (\bank_out[5] [24]), .B1 (n_9), .Y (n_71));
  AOI22XL g6456__9945(.A0 (\bank_out[4] [1]), .A1 (n_10), .B0
       (\bank_out[5] [1]), .B1 (n_9), .Y (n_70));
  AOI22XL g6457__2883(.A0 (\bank_out[0] [1]), .A1 (n_11), .B0
       (\bank_out[1] [1]), .B1 (n_12), .Y (n_69));
  AOI22XL g6458__2346(.A0 (\bank_out[2] [16]), .A1 (n_8), .B0
       (\bank_out[3] [16]), .B1 (n_15), .Y (n_68));
  AOI22XL g6459__1666(.A0 (\bank_out[2] [28]), .A1 (n_8), .B0
       (\bank_out[3] [28]), .B1 (n_15), .Y (n_67));
  AOI22XL g6460__7410(.A0 (\bank_out[4] [0]), .A1 (n_10), .B0
       (\bank_out[5] [0]), .B1 (n_9), .Y (n_66));
  AOI22XL g6461__6417(.A0 (\bank_out[2] [0]), .A1 (n_8), .B0
       (\bank_out[3] [0]), .B1 (n_15), .Y (n_65));
  AOI22XL g6462__5477(.A0 (\bank_out[0] [16]), .A1 (n_11), .B0
       (\bank_out[1] [16]), .B1 (n_12), .Y (n_64));
  AOI22XL g6463__2398(.A0 (\bank_out[2] [24]), .A1 (n_8), .B0
       (\bank_out[3] [24]), .B1 (n_15), .Y (n_63));
  AOI22XL g6464__5107(.A0 (\bank_out[6] [0]), .A1 (n_13), .B0
       (\bank_out[7] [0]), .B1 (n_14), .Y (n_62));
  AOI22XL g6465__6260(.A0 (\bank_out[0] [0]), .A1 (n_11), .B0
       (\bank_out[1] [0]), .B1 (n_12), .Y (n_61));
  AOI22XL g6466__4319(.A0 (\bank_out[6] [28]), .A1 (n_13), .B0
       (\bank_out[7] [28]), .B1 (n_14), .Y (n_60));
  AOI22XL g6467__8428(.A0 (\bank_out[6] [16]), .A1 (n_13), .B0
       (\bank_out[7] [16]), .B1 (n_14), .Y (n_59));
  AOI22XL g6468__5526(.A0 (\bank_out[4] [16]), .A1 (n_10), .B0
       (\bank_out[5] [16]), .B1 (n_9), .Y (n_58));
  AOI22XL g6469__6783(.A0 (\bank_out[6] [24]), .A1 (n_13), .B0
       (\bank_out[7] [24]), .B1 (n_14), .Y (n_57));
  AOI22XL g6470__3680(.A0 (\bank_out[2] [15]), .A1 (n_8), .B0
       (\bank_out[3] [15]), .B1 (n_15), .Y (n_56));
  AOI22XL g6471__1617(.A0 (\bank_out[0] [24]), .A1 (n_11), .B0
       (\bank_out[1] [24]), .B1 (n_12), .Y (n_55));
  AOI22XL g6472__2802(.A0 (\bank_out[0] [15]), .A1 (n_11), .B0
       (\bank_out[1] [15]), .B1 (n_12), .Y (n_54));
  AOI22XL g6473__1705(.A0 (\bank_out[0] [30]), .A1 (n_11), .B0
       (\bank_out[1] [30]), .B1 (n_12), .Y (n_53));
  AOI22XL g6474__5122(.A0 (\bank_out[6] [15]), .A1 (n_13), .B0
       (\bank_out[7] [15]), .B1 (n_14), .Y (n_52));
  AOI22XL g6475__8246(.A0 (\bank_out[4] [28]), .A1 (n_10), .B0
       (\bank_out[5] [28]), .B1 (n_9), .Y (n_51));
  AOI22XL g6476__7098(.A0 (\bank_out[4] [15]), .A1 (n_10), .B0
       (\bank_out[5] [15]), .B1 (n_9), .Y (n_50));
  AOI22XL g6477__6131(.A0 (\bank_out[6] [23]), .A1 (n_13), .B0
       (\bank_out[7] [23]), .B1 (n_14), .Y (n_49));
  AOI22XL g6478__1881(.A0 (\bank_out[2] [14]), .A1 (n_8), .B0
       (\bank_out[3] [14]), .B1 (n_15), .Y (n_48));
  AOI22XL g6479__5115(.A0 (\bank_out[0] [17]), .A1 (n_11), .B0
       (\bank_out[1] [17]), .B1 (n_12), .Y (n_47));
  AOI22XL g6480__7482(.A0 (\bank_out[4] [14]), .A1 (n_10), .B0
       (\bank_out[5] [14]), .B1 (n_9), .Y (n_46));
  AOI22XL g6481__4733(.A0 (\bank_out[0] [23]), .A1 (n_11), .B0
       (\bank_out[1] [23]), .B1 (n_12), .Y (n_45));
  AOI22XL g6482__6161(.A0 (\bank_out[6] [14]), .A1 (n_13), .B0
       (\bank_out[7] [14]), .B1 (n_14), .Y (n_44));
  AOI22XL g6483__9315(.A0 (\bank_out[0] [14]), .A1 (n_11), .B0
       (\bank_out[1] [14]), .B1 (n_12), .Y (n_43));
  AOI22XL g6484__9945(.A0 (\bank_out[4] [23]), .A1 (n_10), .B0
       (\bank_out[5] [23]), .B1 (n_9), .Y (n_42));
  AOI22XL g6485__2883(.A0 (\bank_out[6] [13]), .A1 (n_13), .B0
       (\bank_out[7] [13]), .B1 (n_14), .Y (n_41));
  AOI22XL g6486__2346(.A0 (\bank_out[2] [23]), .A1 (n_8), .B0
       (\bank_out[3] [23]), .B1 (n_15), .Y (n_40));
  AOI22XL g6487__1666(.A0 (\bank_out[2] [13]), .A1 (n_8), .B0
       (\bank_out[3] [13]), .B1 (n_15), .Y (n_39));
  AOI22XL g6488__7410(.A0 (\bank_out[4] [30]), .A1 (n_10), .B0
       (\bank_out[5] [30]), .B1 (n_9), .Y (n_38));
  AOI22XL g6489__6417(.A0 (\bank_out[4] [13]), .A1 (n_10), .B0
       (\bank_out[5] [13]), .B1 (n_9), .Y (n_37));
  AOI22XL g6490__5477(.A0 (\bank_out[0] [22]), .A1 (n_11), .B0
       (\bank_out[1] [22]), .B1 (n_12), .Y (n_36));
  AOI22XL g6491__2398(.A0 (\bank_out[0] [13]), .A1 (n_11), .B0
       (\bank_out[1] [13]), .B1 (n_12), .Y (n_35));
  AOI22XL g6492__5107(.A0 (\bank_out[6] [12]), .A1 (n_13), .B0
       (\bank_out[7] [12]), .B1 (n_14), .Y (n_34));
  AOI22XL g6493__6260(.A0 (\bank_out[6] [31]), .A1 (n_13), .B0
       (\bank_out[7] [31]), .B1 (n_14), .Y (n_33));
  AOI22XL g6494__4319(.A0 (\bank_out[0] [12]), .A1 (n_11), .B0
       (\bank_out[1] [12]), .B1 (n_12), .Y (n_32));
  AOI22XL g6495__8428(.A0 (\bank_out[4] [22]), .A1 (n_10), .B0
       (\bank_out[5] [22]), .B1 (n_9), .Y (n_31));
  AOI22XL g6496__5526(.A0 (\bank_out[6] [27]), .A1 (n_13), .B0
       (\bank_out[7] [27]), .B1 (n_14), .Y (n_30));
  AOI22XL g6497__6783(.A0 (\bank_out[4] [12]), .A1 (n_10), .B0
       (\bank_out[5] [12]), .B1 (n_9), .Y (n_29));
  AOI22XL g6498__3680(.A0 (\bank_out[2] [12]), .A1 (n_8), .B0
       (\bank_out[3] [12]), .B1 (n_15), .Y (n_28));
  AOI22XL g6499__1617(.A0 (\bank_out[0] [27]), .A1 (n_11), .B0
       (\bank_out[1] [27]), .B1 (n_12), .Y (n_27));
  AOI22XL g6500__2802(.A0 (\bank_out[6] [22]), .A1 (n_13), .B0
       (\bank_out[7] [22]), .B1 (n_14), .Y (n_26));
  AOI22XL g6501__1705(.A0 (\bank_out[2] [30]), .A1 (n_8), .B0
       (\bank_out[3] [30]), .B1 (n_15), .Y (n_25));
  AOI22XL g6502__5122(.A0 (\bank_out[2] [11]), .A1 (n_8), .B0
       (\bank_out[3] [11]), .B1 (n_15), .Y (n_24));
  AOI22XL g6503__8246(.A0 (\bank_out[6] [11]), .A1 (n_13), .B0
       (\bank_out[7] [11]), .B1 (n_14), .Y (n_23));
  AOI22XL g6504__7098(.A0 (\bank_out[2] [22]), .A1 (n_8), .B0
       (\bank_out[3] [22]), .B1 (n_15), .Y (n_22));
  AOI22XL g6505__6131(.A0 (\bank_out[4] [11]), .A1 (n_10), .B0
       (\bank_out[5] [11]), .B1 (n_9), .Y (n_21));
  AOI22XL g6506__1881(.A0 (\bank_out[0] [11]), .A1 (n_11), .B0
       (\bank_out[1] [11]), .B1 (n_12), .Y (n_20));
  AOI22XL g6507__5115(.A0 (\bank_out[4] [27]), .A1 (n_10), .B0
       (\bank_out[5] [27]), .B1 (n_9), .Y (n_19));
  AOI22XL g6508__7482(.A0 (\bank_out[6] [21]), .A1 (n_13), .B0
       (\bank_out[7] [21]), .B1 (n_14), .Y (n_18));
  AOI22XL g6509__4733(.A0 (\bank_out[6] [10]), .A1 (n_13), .B0
       (\bank_out[7] [10]), .B1 (n_14), .Y (n_17));
  AOI22XL g6510__6161(.A0 (\bank_out[2] [10]), .A1 (n_8), .B0
       (\bank_out[3] [10]), .B1 (n_15), .Y (n_16));
  NAND2XL g6511__9315(.A (n_1), .B (n_12), .Y (bank_we[1]));
  NAND2XL g6512__9945(.A (n_1), .B (n_8), .Y (bank_we[2]));
  NAND2XL g6513__2883(.A (n_1), .B (n_15), .Y (bank_we[3]));
  NAND2XL g6514__2346(.A (n_1), .B (n_11), .Y (bank_we[0]));
  NAND2XL g6515__1666(.A (n_1), .B (n_13), .Y (bank_we[6]));
  NAND2XL g6516__7410(.A (n_1), .B (n_14), .Y (bank_we[7]));
  NAND2XL g6517__6417(.A (n_1), .B (n_10), .Y (bank_we[4]));
  NAND2XL g6518__5477(.A (n_1), .B (n_9), .Y (bank_we[5]));
  INVX1 g6519(.A (n_15), .Y (bank_select[3]));
  INVX1 g6520(.A (n_14), .Y (bank_select[7]));
  INVX1 g6521(.A (n_13), .Y (bank_select[6]));
  INVX1 g6522(.A (n_12), .Y (bank_select[1]));
  AND2X2 g6523__2398(.A (n_5), .B (A[7]), .Y (n_15));
  AND2X2 g6524__5107(.A (n_0), .B (A[7]), .Y (n_14));
  AND2X2 g6525__6260(.A (n_7), .B (A[7]), .Y (n_13));
  AND2X2 g6526__4319(.A (n_5), .B (n_2), .Y (n_12));
  INVX1 g6527(.A (n_11), .Y (n_145));
  INVX1 g6528(.A (n_10), .Y (bank_select[4]));
  INVX1 g6529(.A (n_9), .Y (bank_select[5]));
  INVX1 g6530(.A (n_8), .Y (bank_select[2]));
  AND2X2 g6531__8428(.A (n_6), .B (n_2), .Y (n_11));
  AND2X2 g6532__5526(.A (n_7), .B (n_2), .Y (n_10));
  AND2X2 g6533__6783(.A (n_0), .B (n_2), .Y (n_9));
  AND2X2 g6534__3680(.A (n_6), .B (A[7]), .Y (n_8));
  AND2X1 g6535__1617(.A (n_3), .B (A[8]), .Y (n_7));
  NOR2BXL g6536__2802(.AN (n_3), .B (A[8]), .Y (n_6));
  NOR2XL g6538__1705(.A (n_4), .B (A[8]), .Y (n_5));
  NAND2BXL g6540__5122(.AN (CEN), .B (A[6]), .Y (n_4));
  NOR2XL g6541__8246(.A (CEN), .B (A[6]), .Y (n_3));
  INVX1 g6542(.A (A[7]), .Y (n_2));
  INVX1 g6543(.A (GWEN), .Y (n_1));
  NOR2BX1 g2__7098(.AN (A[8]), .B (n_4), .Y (n_0));
endmodule

