
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  2 2025 15:22:23 IST (May  2 2025 09:52:23 UTC)

// Verification Directory fv/sram_sp_512d_32w_4m_2b 

module sram_sp_512d_32w_4m_2b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [8:0] A;
  input [31:0] D, WEN;
  output [31:0] Q;
  wire CLK, CEN, GWEN;
  wire [8:0] A;
  wire [31:0] D, WEN;
  wire [31:0] Q;
  wire [7:0] bank_we;
  wire [31:0] \bank_out[0] ;
  wire [7:0] bank_select;
  wire [31:0] \bank_out[1] ;
  wire [31:0] \bank_out[2] ;
  wire [31:0] \bank_out[3] ;
  wire [31:0] \bank_out[4] ;
  wire [31:0] \bank_out[5] ;
  wire [31:0] \bank_out[6] ;
  wire [31:0] \bank_out[7] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_145, n_214;
  SPRAM_64x32 \MEM_BANKS[0].bank (.CE (n_214), .OEB (1'b0), .CSB
       (n_145), .WEB (bank_we[0]), .A (A[5:0]), .I (D), .O
       (\bank_out[0] ));
  SPRAM_64x32 \MEM_BANKS[1].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[1]), .WEB (bank_we[1]), .A (A[5:0]), .I (D), .O
       (\bank_out[1] ));
  SPRAM_64x32 \MEM_BANKS[2].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[2]), .WEB (bank_we[2]), .A (A[5:0]), .I (D), .O
       (\bank_out[2] ));
  SPRAM_64x32 \MEM_BANKS[3].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[3]), .WEB (bank_we[3]), .A (A[5:0]), .I (D), .O
       (\bank_out[3] ));
  SPRAM_64x32 \MEM_BANKS[4].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[4]), .WEB (bank_we[4]), .A (A[5:0]), .I (D), .O
       (\bank_out[4] ));
  SPRAM_64x32 \MEM_BANKS[5].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[5]), .WEB (bank_we[5]), .A (A[5:0]), .I (D), .O
       (\bank_out[5] ));
  SPRAM_64x32 \MEM_BANKS[6].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[6]), .WEB (bank_we[6]), .A (A[5:0]), .I (D), .O
       (\bank_out[6] ));
  SPRAM_64x32 \MEM_BANKS[7].bank (.CE (n_214), .OEB (1'b0), .CSB
       (bank_select[7]), .WEB (bank_we[7]), .A (A[5:0]), .I (D), .O
       (\bank_out[7] ));
  inv0d0 g1501(.I (CEN), .ZN (n_214));
  nd04d0 g6372__2398(.A1 (n_97), .A2 (n_95), .A3 (n_92), .A4 (n_91),
       .ZN (Q[4]));
  nd04d0 g6373__5107(.A1 (n_96), .A2 (n_53), .A3 (n_38), .A4 (n_25),
       .ZN (Q[30]));
  nd04d0 g6374__6260(.A1 (n_134), .A2 (n_118), .A3 (n_103), .A4 (n_93),
       .ZN (Q[29]));
  nd04d0 g6375__4319(.A1 (n_132), .A2 (n_126), .A3 (n_116), .A4
       (n_109), .ZN (Q[26]));
  nd04d0 g6376__8428(.A1 (n_138), .A2 (n_135), .A3 (n_133), .A4
       (n_131), .ZN (Q[9]));
  nd04d0 g6377__5526(.A1 (n_130), .A2 (n_127), .A3 (n_122), .A4
       (n_120), .ZN (Q[20]));
  nd04d0 g6378__6783(.A1 (n_129), .A2 (n_128), .A3 (n_125), .A4
       (n_124), .ZN (Q[8]));
  nd04d0 g6379__3680(.A1 (n_121), .A2 (n_119), .A3 (n_117), .A4
       (n_115), .ZN (Q[7]));
  nd04d0 g6380__1617(.A1 (n_99), .A2 (n_90), .A3 (n_83), .A4 (n_81),
       .ZN (Q[25]));
  nd04d0 g6381__2802(.A1 (n_113), .A2 (n_143), .A3 (n_107), .A4
       (n_105), .ZN (Q[19]));
  nd04d0 g6382__1705(.A1 (n_114), .A2 (n_112), .A3 (n_110), .A4
       (n_108), .ZN (Q[6]));
  nd04d0 g6383__5122(.A1 (n_98), .A2 (n_94), .A3 (n_89), .A4 (n_86),
       .ZN (Q[18]));
  nd04d0 g6384__8246(.A1 (n_106), .A2 (n_104), .A3 (n_102), .A4
       (n_100), .ZN (Q[5]));
  nd04d0 g6385__7098(.A1 (n_67), .A2 (n_60), .A3 (n_51), .A4 (n_79),
       .ZN (Q[28]));
  nd04d0 g6386__6131(.A1 (n_82), .A2 (n_47), .A3 (n_75), .A4 (n_73),
       .ZN (Q[17]));
  nd04d0 g6387__1881(.A1 (n_123), .A2 (n_101), .A3 (n_33), .A4 (n_137),
       .ZN (Q[31]));
  nd04d0 g6388__5115(.A1 (n_17), .A2 (n_16), .A3 (n_142), .A4 (n_141),
       .ZN (Q[10]));
  nd04d0 g6389__7482(.A1 (n_77), .A2 (n_80), .A3 (n_78), .A4 (n_76),
       .ZN (Q[2]));
  nd04d0 g6390__4733(.A1 (n_71), .A2 (n_63), .A3 (n_57), .A4 (n_55),
       .ZN (Q[24]));
  nd04d0 g6391__6161(.A1 (n_68), .A2 (n_64), .A3 (n_59), .A4 (n_58),
       .ZN (Q[16]));
  nd04d0 g6392__9315(.A1 (n_74), .A2 (n_72), .A3 (n_70), .A4 (n_69),
       .ZN (Q[1]));
  nd04d0 g6393__9945(.A1 (n_66), .A2 (n_65), .A3 (n_62), .A4 (n_61),
       .ZN (Q[0]));
  nd04d0 g6394__2883(.A1 (n_30), .A2 (n_27), .A3 (n_19), .A4 (n_140),
       .ZN (Q[27]));
  nd04d0 g6395__2346(.A1 (n_49), .A2 (n_45), .A3 (n_42), .A4 (n_40),
       .ZN (Q[23]));
  nd04d0 g6396__1666(.A1 (n_56), .A2 (n_54), .A3 (n_52), .A4 (n_50),
       .ZN (Q[15]));
  nd04d0 g6397__7410(.A1 (n_48), .A2 (n_46), .A3 (n_44), .A4 (n_43),
       .ZN (Q[14]));
  nd04d0 g6398__6417(.A1 (n_41), .A2 (n_39), .A3 (n_37), .A4 (n_35),
       .ZN (Q[13]));
  nd04d0 g6399__5477(.A1 (n_36), .A2 (n_31), .A3 (n_26), .A4 (n_22),
       .ZN (Q[22]));
  nd04d0 g6400__2398(.A1 (n_34), .A2 (n_32), .A3 (n_29), .A4 (n_28),
       .ZN (Q[12]));
  nd04d0 g6401__5107(.A1 (n_24), .A2 (n_23), .A3 (n_21), .A4 (n_20),
       .ZN (Q[11]));
  nd04d0 g6402__6260(.A1 (n_18), .A2 (n_111), .A3 (n_139), .A4 (n_136),
       .ZN (Q[21]));
  nd04d0 g6403__4319(.A1 (n_88), .A2 (n_87), .A3 (n_85), .A4 (n_84),
       .ZN (Q[3]));
  aoi22d1 g6404__8428(.A1 (\bank_out[6] [19]), .A2 (n_13), .B1
       (\bank_out[7] [19]), .B2 (n_15), .ZN (n_143));
  aoi22d1 g6405__5526(.A1 (\bank_out[4] [10]), .A2 (n_10), .B1
       (\bank_out[5] [10]), .B2 (n_9), .ZN (n_142));
  aoi22d1 g6406__6783(.A1 (\bank_out[0] [10]), .A2 (n_11), .B1
       (\bank_out[1] [10]), .B2 (n_14), .ZN (n_141));
  aoi22d1 g6407__3680(.A1 (\bank_out[2] [27]), .A2 (n_8), .B1
       (\bank_out[3] [27]), .B2 (n_12), .ZN (n_140));
  aoi22d1 g6408__1617(.A1 (\bank_out[4] [21]), .A2 (n_10), .B1
       (\bank_out[5] [21]), .B2 (n_9), .ZN (n_139));
  aoi22d1 g6409__2802(.A1 (\bank_out[0] [9]), .A2 (n_11), .B1
       (\bank_out[1] [9]), .B2 (n_14), .ZN (n_138));
  aoi22d1 g6410__1705(.A1 (\bank_out[0] [31]), .A2 (n_11), .B1
       (\bank_out[1] [31]), .B2 (n_14), .ZN (n_137));
  aoi22d1 g6411__5122(.A1 (\bank_out[2] [21]), .A2 (n_8), .B1
       (\bank_out[3] [21]), .B2 (n_12), .ZN (n_136));
  aoi22d1 g6412__8246(.A1 (\bank_out[6] [9]), .A2 (n_13), .B1
       (\bank_out[7] [9]), .B2 (n_15), .ZN (n_135));
  aoi22d1 g6413__7098(.A1 (\bank_out[6] [29]), .A2 (n_13), .B1
       (\bank_out[7] [29]), .B2 (n_15), .ZN (n_134));
  aoi22d1 g6414__6131(.A1 (\bank_out[4] [9]), .A2 (n_10), .B1
       (\bank_out[5] [9]), .B2 (n_9), .ZN (n_133));
  aoi22d1 g6415__1881(.A1 (\bank_out[0] [26]), .A2 (n_11), .B1
       (\bank_out[1] [26]), .B2 (n_14), .ZN (n_132));
  aoi22d1 g6416__5115(.A1 (\bank_out[2] [9]), .A2 (n_8), .B1
       (\bank_out[3] [9]), .B2 (n_12), .ZN (n_131));
  aoi22d1 g6417__7482(.A1 (\bank_out[4] [20]), .A2 (n_10), .B1
       (\bank_out[5] [20]), .B2 (n_9), .ZN (n_130));
  aoi22d1 g6418__4733(.A1 (\bank_out[2] [8]), .A2 (n_8), .B1
       (\bank_out[3] [8]), .B2 (n_12), .ZN (n_129));
  aoi22d1 g6419__6161(.A1 (\bank_out[0] [8]), .A2 (n_11), .B1
       (\bank_out[1] [8]), .B2 (n_14), .ZN (n_128));
  aoi22d1 g6420__9315(.A1 (\bank_out[2] [20]), .A2 (n_8), .B1
       (\bank_out[3] [20]), .B2 (n_12), .ZN (n_127));
  aoi22d1 g6421__9945(.A1 (\bank_out[6] [26]), .A2 (n_13), .B1
       (\bank_out[7] [26]), .B2 (n_15), .ZN (n_126));
  aoi22d1 g6422__2883(.A1 (\bank_out[6] [8]), .A2 (n_13), .B1
       (\bank_out[7] [8]), .B2 (n_15), .ZN (n_125));
  aoi22d1 g6423__2346(.A1 (\bank_out[4] [8]), .A2 (n_10), .B1
       (\bank_out[5] [8]), .B2 (n_9), .ZN (n_124));
  aoi22d1 g6424__1666(.A1 (\bank_out[4] [31]), .A2 (n_10), .B1
       (\bank_out[5] [31]), .B2 (n_9), .ZN (n_123));
  aoi22d1 g6425__7410(.A1 (\bank_out[6] [20]), .A2 (n_13), .B1
       (\bank_out[7] [20]), .B2 (n_15), .ZN (n_122));
  aoi22d1 g6426__6417(.A1 (\bank_out[6] [7]), .A2 (n_13), .B1
       (\bank_out[7] [7]), .B2 (n_15), .ZN (n_121));
  aoi22d1 g6427__5477(.A1 (\bank_out[0] [20]), .A2 (n_11), .B1
       (\bank_out[1] [20]), .B2 (n_14), .ZN (n_120));
  aoi22d1 g6428__2398(.A1 (\bank_out[2] [7]), .A2 (n_8), .B1
       (\bank_out[3] [7]), .B2 (n_12), .ZN (n_119));
  aoi22d1 g6429__5107(.A1 (\bank_out[0] [29]), .A2 (n_11), .B1
       (\bank_out[1] [29]), .B2 (n_14), .ZN (n_118));
  aoi22d1 g6430__6260(.A1 (\bank_out[4] [7]), .A2 (n_10), .B1
       (\bank_out[5] [7]), .B2 (n_9), .ZN (n_117));
  aoi22d1 g6431__4319(.A1 (\bank_out[4] [26]), .A2 (n_10), .B1
       (\bank_out[5] [26]), .B2 (n_9), .ZN (n_116));
  aoi22d1 g6432__8428(.A1 (\bank_out[0] [7]), .A2 (n_11), .B1
       (\bank_out[1] [7]), .B2 (n_14), .ZN (n_115));
  aoi22d1 g6433__5526(.A1 (\bank_out[2] [6]), .A2 (n_8), .B1
       (\bank_out[3] [6]), .B2 (n_12), .ZN (n_114));
  aoi22d1 g6434__6783(.A1 (\bank_out[2] [19]), .A2 (n_8), .B1
       (\bank_out[3] [19]), .B2 (n_12), .ZN (n_113));
  aoi22d1 g6435__3680(.A1 (\bank_out[0] [6]), .A2 (n_11), .B1
       (\bank_out[1] [6]), .B2 (n_14), .ZN (n_112));
  aoi22d1 g6436__1617(.A1 (\bank_out[0] [21]), .A2 (n_11), .B1
       (\bank_out[1] [21]), .B2 (n_14), .ZN (n_111));
  aoi22d1 g6437__2802(.A1 (\bank_out[6] [6]), .A2 (n_13), .B1
       (\bank_out[7] [6]), .B2 (n_15), .ZN (n_110));
  aoi22d1 g6438__1705(.A1 (\bank_out[2] [26]), .A2 (n_8), .B1
       (\bank_out[3] [26]), .B2 (n_12), .ZN (n_109));
  aoi22d1 g6439__5122(.A1 (\bank_out[4] [6]), .A2 (n_10), .B1
       (\bank_out[5] [6]), .B2 (n_9), .ZN (n_108));
  aoi22d1 g6440__8246(.A1 (\bank_out[4] [19]), .A2 (n_10), .B1
       (\bank_out[5] [19]), .B2 (n_9), .ZN (n_107));
  aoi22d1 g6441__7098(.A1 (\bank_out[0] [5]), .A2 (n_11), .B1
       (\bank_out[1] [5]), .B2 (n_14), .ZN (n_106));
  aoi22d1 g6442__6131(.A1 (\bank_out[0] [19]), .A2 (n_11), .B1
       (\bank_out[1] [19]), .B2 (n_14), .ZN (n_105));
  aoi22d1 g6443__1881(.A1 (\bank_out[6] [5]), .A2 (n_13), .B1
       (\bank_out[7] [5]), .B2 (n_15), .ZN (n_104));
  aoi22d1 g6444__5115(.A1 (\bank_out[4] [29]), .A2 (n_10), .B1
       (\bank_out[5] [29]), .B2 (n_9), .ZN (n_103));
  aoi22d1 g6445__7482(.A1 (\bank_out[4] [5]), .A2 (n_10), .B1
       (\bank_out[5] [5]), .B2 (n_9), .ZN (n_102));
  aoi22d1 g6446__4733(.A1 (\bank_out[2] [31]), .A2 (n_8), .B1
       (\bank_out[3] [31]), .B2 (n_12), .ZN (n_101));
  aoi22d1 g6447__6161(.A1 (\bank_out[2] [5]), .A2 (n_8), .B1
       (\bank_out[3] [5]), .B2 (n_12), .ZN (n_100));
  aoi22d1 g6448__9315(.A1 (\bank_out[6] [25]), .A2 (n_13), .B1
       (\bank_out[7] [25]), .B2 (n_15), .ZN (n_99));
  aoi22d1 g6449__9945(.A1 (\bank_out[6] [18]), .A2 (n_13), .B1
       (\bank_out[7] [18]), .B2 (n_15), .ZN (n_98));
  aoi22d1 g6450__2883(.A1 (\bank_out[4] [4]), .A2 (n_10), .B1
       (\bank_out[5] [4]), .B2 (n_9), .ZN (n_97));
  aoi22d1 g6451__2346(.A1 (\bank_out[6] [30]), .A2 (n_13), .B1
       (\bank_out[7] [30]), .B2 (n_15), .ZN (n_96));
  aoi22d1 g6452__1666(.A1 (\bank_out[0] [4]), .A2 (n_11), .B1
       (\bank_out[1] [4]), .B2 (n_14), .ZN (n_95));
  aoi22d1 g6453__7410(.A1 (\bank_out[2] [18]), .A2 (n_8), .B1
       (\bank_out[3] [18]), .B2 (n_12), .ZN (n_94));
  aoi22d1 g6454__6417(.A1 (\bank_out[2] [29]), .A2 (n_8), .B1
       (\bank_out[3] [29]), .B2 (n_12), .ZN (n_93));
  aoi22d1 g6455__5477(.A1 (\bank_out[6] [4]), .A2 (n_13), .B1
       (\bank_out[7] [4]), .B2 (n_15), .ZN (n_92));
  aoi22d1 g6456__2398(.A1 (\bank_out[2] [4]), .A2 (n_8), .B1
       (\bank_out[3] [4]), .B2 (n_12), .ZN (n_91));
  aoi22d1 g6457__5107(.A1 (\bank_out[4] [25]), .A2 (n_10), .B1
       (\bank_out[5] [25]), .B2 (n_9), .ZN (n_90));
  aoi22d1 g6458__6260(.A1 (\bank_out[4] [18]), .A2 (n_10), .B1
       (\bank_out[5] [18]), .B2 (n_9), .ZN (n_89));
  aoi22d1 g6459__4319(.A1 (\bank_out[4] [3]), .A2 (n_10), .B1
       (\bank_out[5] [3]), .B2 (n_9), .ZN (n_88));
  aoi22d1 g6460__8428(.A1 (\bank_out[0] [3]), .A2 (n_11), .B1
       (\bank_out[1] [3]), .B2 (n_14), .ZN (n_87));
  aoi22d1 g6461__5526(.A1 (\bank_out[0] [18]), .A2 (n_11), .B1
       (\bank_out[1] [18]), .B2 (n_14), .ZN (n_86));
  aoi22d1 g6462__6783(.A1 (\bank_out[6] [3]), .A2 (n_13), .B1
       (\bank_out[7] [3]), .B2 (n_15), .ZN (n_85));
  aoi22d1 g6463__3680(.A1 (\bank_out[2] [3]), .A2 (n_8), .B1
       (\bank_out[3] [3]), .B2 (n_12), .ZN (n_84));
  aoi22d1 g6464__1617(.A1 (\bank_out[2] [25]), .A2 (n_8), .B1
       (\bank_out[3] [25]), .B2 (n_12), .ZN (n_83));
  aoi22d1 g6465__2802(.A1 (\bank_out[2] [17]), .A2 (n_8), .B1
       (\bank_out[3] [17]), .B2 (n_12), .ZN (n_82));
  aoi22d1 g6466__1705(.A1 (\bank_out[0] [25]), .A2 (n_11), .B1
       (\bank_out[1] [25]), .B2 (n_14), .ZN (n_81));
  aoi22d1 g6467__5122(.A1 (\bank_out[0] [2]), .A2 (n_11), .B1
       (\bank_out[1] [2]), .B2 (n_14), .ZN (n_80));
  aoi22d1 g6468__8246(.A1 (\bank_out[0] [28]), .A2 (n_11), .B1
       (\bank_out[1] [28]), .B2 (n_14), .ZN (n_79));
  aoi22d1 g6469__7098(.A1 (\bank_out[4] [2]), .A2 (n_10), .B1
       (\bank_out[5] [2]), .B2 (n_9), .ZN (n_78));
  aoi22d1 g6470__6131(.A1 (\bank_out[6] [2]), .A2 (n_13), .B1
       (\bank_out[7] [2]), .B2 (n_15), .ZN (n_77));
  aoi22d1 g6471__1881(.A1 (\bank_out[2] [2]), .A2 (n_8), .B1
       (\bank_out[3] [2]), .B2 (n_12), .ZN (n_76));
  aoi22d1 g6472__5115(.A1 (\bank_out[6] [17]), .A2 (n_13), .B1
       (\bank_out[7] [17]), .B2 (n_15), .ZN (n_75));
  aoi22d1 g6473__7482(.A1 (\bank_out[2] [1]), .A2 (n_8), .B1
       (\bank_out[3] [1]), .B2 (n_12), .ZN (n_74));
  aoi22d1 g6474__4733(.A1 (\bank_out[4] [17]), .A2 (n_10), .B1
       (\bank_out[5] [17]), .B2 (n_9), .ZN (n_73));
  aoi22d1 g6475__6161(.A1 (\bank_out[6] [1]), .A2 (n_13), .B1
       (\bank_out[7] [1]), .B2 (n_15), .ZN (n_72));
  aoi22d1 g6476__9315(.A1 (\bank_out[4] [24]), .A2 (n_10), .B1
       (\bank_out[5] [24]), .B2 (n_9), .ZN (n_71));
  aoi22d1 g6477__9945(.A1 (\bank_out[4] [1]), .A2 (n_10), .B1
       (\bank_out[5] [1]), .B2 (n_9), .ZN (n_70));
  aoi22d1 g6478__2883(.A1 (\bank_out[0] [1]), .A2 (n_11), .B1
       (\bank_out[1] [1]), .B2 (n_14), .ZN (n_69));
  aoi22d1 g6479__2346(.A1 (\bank_out[2] [16]), .A2 (n_8), .B1
       (\bank_out[3] [16]), .B2 (n_12), .ZN (n_68));
  aoi22d1 g6480__1666(.A1 (\bank_out[2] [28]), .A2 (n_8), .B1
       (\bank_out[3] [28]), .B2 (n_12), .ZN (n_67));
  aoi22d1 g6481__7410(.A1 (\bank_out[4] [0]), .A2 (n_10), .B1
       (\bank_out[5] [0]), .B2 (n_9), .ZN (n_66));
  aoi22d1 g6482__6417(.A1 (\bank_out[2] [0]), .A2 (n_8), .B1
       (\bank_out[3] [0]), .B2 (n_12), .ZN (n_65));
  aoi22d1 g6483__5477(.A1 (\bank_out[0] [16]), .A2 (n_11), .B1
       (\bank_out[1] [16]), .B2 (n_14), .ZN (n_64));
  aoi22d1 g6484__2398(.A1 (\bank_out[2] [24]), .A2 (n_8), .B1
       (\bank_out[3] [24]), .B2 (n_12), .ZN (n_63));
  aoi22d1 g6485__5107(.A1 (\bank_out[6] [0]), .A2 (n_13), .B1
       (\bank_out[7] [0]), .B2 (n_15), .ZN (n_62));
  aoi22d1 g6486__6260(.A1 (\bank_out[0] [0]), .A2 (n_11), .B1
       (\bank_out[1] [0]), .B2 (n_14), .ZN (n_61));
  aoi22d1 g6487__4319(.A1 (\bank_out[6] [28]), .A2 (n_13), .B1
       (\bank_out[7] [28]), .B2 (n_15), .ZN (n_60));
  aoi22d1 g6488__8428(.A1 (\bank_out[6] [16]), .A2 (n_13), .B1
       (\bank_out[7] [16]), .B2 (n_15), .ZN (n_59));
  aoi22d1 g6489__5526(.A1 (\bank_out[4] [16]), .A2 (n_10), .B1
       (\bank_out[5] [16]), .B2 (n_9), .ZN (n_58));
  aoi22d1 g6490__6783(.A1 (\bank_out[6] [24]), .A2 (n_13), .B1
       (\bank_out[7] [24]), .B2 (n_15), .ZN (n_57));
  aoi22d1 g6491__3680(.A1 (\bank_out[2] [15]), .A2 (n_8), .B1
       (\bank_out[3] [15]), .B2 (n_12), .ZN (n_56));
  aoi22d1 g6492__1617(.A1 (\bank_out[0] [24]), .A2 (n_11), .B1
       (\bank_out[1] [24]), .B2 (n_14), .ZN (n_55));
  aoi22d1 g6493__2802(.A1 (\bank_out[0] [15]), .A2 (n_11), .B1
       (\bank_out[1] [15]), .B2 (n_14), .ZN (n_54));
  aoi22d1 g6494__1705(.A1 (\bank_out[0] [30]), .A2 (n_11), .B1
       (\bank_out[1] [30]), .B2 (n_14), .ZN (n_53));
  aoi22d1 g6495__5122(.A1 (\bank_out[6] [15]), .A2 (n_13), .B1
       (\bank_out[7] [15]), .B2 (n_15), .ZN (n_52));
  aoi22d1 g6496__8246(.A1 (\bank_out[4] [28]), .A2 (n_10), .B1
       (\bank_out[5] [28]), .B2 (n_9), .ZN (n_51));
  aoi22d1 g6497__7098(.A1 (\bank_out[4] [15]), .A2 (n_10), .B1
       (\bank_out[5] [15]), .B2 (n_9), .ZN (n_50));
  aoi22d1 g6498__6131(.A1 (\bank_out[6] [23]), .A2 (n_13), .B1
       (\bank_out[7] [23]), .B2 (n_15), .ZN (n_49));
  aoi22d1 g6499__1881(.A1 (\bank_out[2] [14]), .A2 (n_8), .B1
       (\bank_out[3] [14]), .B2 (n_12), .ZN (n_48));
  aoi22d1 g6500__5115(.A1 (\bank_out[0] [17]), .A2 (n_11), .B1
       (\bank_out[1] [17]), .B2 (n_14), .ZN (n_47));
  aoi22d1 g6501__7482(.A1 (\bank_out[4] [14]), .A2 (n_10), .B1
       (\bank_out[5] [14]), .B2 (n_9), .ZN (n_46));
  aoi22d1 g6502__4733(.A1 (\bank_out[0] [23]), .A2 (n_11), .B1
       (\bank_out[1] [23]), .B2 (n_14), .ZN (n_45));
  aoi22d1 g6503__6161(.A1 (\bank_out[6] [14]), .A2 (n_13), .B1
       (\bank_out[7] [14]), .B2 (n_15), .ZN (n_44));
  aoi22d1 g6504__9315(.A1 (\bank_out[0] [14]), .A2 (n_11), .B1
       (\bank_out[1] [14]), .B2 (n_14), .ZN (n_43));
  aoi22d1 g6505__9945(.A1 (\bank_out[4] [23]), .A2 (n_10), .B1
       (\bank_out[5] [23]), .B2 (n_9), .ZN (n_42));
  aoi22d1 g6506__2883(.A1 (\bank_out[6] [13]), .A2 (n_13), .B1
       (\bank_out[7] [13]), .B2 (n_15), .ZN (n_41));
  aoi22d1 g6507__2346(.A1 (\bank_out[2] [23]), .A2 (n_8), .B1
       (\bank_out[3] [23]), .B2 (n_12), .ZN (n_40));
  aoi22d1 g6508__1666(.A1 (\bank_out[2] [13]), .A2 (n_8), .B1
       (\bank_out[3] [13]), .B2 (n_12), .ZN (n_39));
  aoi22d1 g6509__7410(.A1 (\bank_out[4] [30]), .A2 (n_10), .B1
       (\bank_out[5] [30]), .B2 (n_9), .ZN (n_38));
  aoi22d1 g6510__6417(.A1 (\bank_out[4] [13]), .A2 (n_10), .B1
       (\bank_out[5] [13]), .B2 (n_9), .ZN (n_37));
  aoi22d1 g6511__5477(.A1 (\bank_out[0] [22]), .A2 (n_11), .B1
       (\bank_out[1] [22]), .B2 (n_14), .ZN (n_36));
  aoi22d1 g6512__2398(.A1 (\bank_out[0] [13]), .A2 (n_11), .B1
       (\bank_out[1] [13]), .B2 (n_14), .ZN (n_35));
  aoi22d1 g6513__5107(.A1 (\bank_out[6] [12]), .A2 (n_13), .B1
       (\bank_out[7] [12]), .B2 (n_15), .ZN (n_34));
  aoi22d1 g6514__6260(.A1 (\bank_out[6] [31]), .A2 (n_13), .B1
       (\bank_out[7] [31]), .B2 (n_15), .ZN (n_33));
  aoi22d1 g6515__4319(.A1 (\bank_out[0] [12]), .A2 (n_11), .B1
       (\bank_out[1] [12]), .B2 (n_14), .ZN (n_32));
  aoi22d1 g6516__8428(.A1 (\bank_out[4] [22]), .A2 (n_10), .B1
       (\bank_out[5] [22]), .B2 (n_9), .ZN (n_31));
  aoi22d1 g6517__5526(.A1 (\bank_out[6] [27]), .A2 (n_13), .B1
       (\bank_out[7] [27]), .B2 (n_15), .ZN (n_30));
  aoi22d1 g6518__6783(.A1 (\bank_out[4] [12]), .A2 (n_10), .B1
       (\bank_out[5] [12]), .B2 (n_9), .ZN (n_29));
  aoi22d1 g6519__3680(.A1 (\bank_out[2] [12]), .A2 (n_8), .B1
       (\bank_out[3] [12]), .B2 (n_12), .ZN (n_28));
  aoi22d1 g6520__1617(.A1 (\bank_out[0] [27]), .A2 (n_11), .B1
       (\bank_out[1] [27]), .B2 (n_14), .ZN (n_27));
  aoi22d1 g6521__2802(.A1 (\bank_out[6] [22]), .A2 (n_13), .B1
       (\bank_out[7] [22]), .B2 (n_15), .ZN (n_26));
  aoi22d1 g6522__1705(.A1 (\bank_out[2] [30]), .A2 (n_8), .B1
       (\bank_out[3] [30]), .B2 (n_12), .ZN (n_25));
  aoi22d1 g6523__5122(.A1 (\bank_out[2] [11]), .A2 (n_8), .B1
       (\bank_out[3] [11]), .B2 (n_12), .ZN (n_24));
  aoi22d1 g6524__8246(.A1 (\bank_out[6] [11]), .A2 (n_13), .B1
       (\bank_out[7] [11]), .B2 (n_15), .ZN (n_23));
  aoi22d1 g6525__7098(.A1 (\bank_out[2] [22]), .A2 (n_8), .B1
       (\bank_out[3] [22]), .B2 (n_12), .ZN (n_22));
  aoi22d1 g6526__6131(.A1 (\bank_out[4] [11]), .A2 (n_10), .B1
       (\bank_out[5] [11]), .B2 (n_9), .ZN (n_21));
  aoi22d1 g6527__1881(.A1 (\bank_out[0] [11]), .A2 (n_11), .B1
       (\bank_out[1] [11]), .B2 (n_14), .ZN (n_20));
  aoi22d1 g6528__5115(.A1 (\bank_out[4] [27]), .A2 (n_10), .B1
       (\bank_out[5] [27]), .B2 (n_9), .ZN (n_19));
  aoi22d1 g6529__7482(.A1 (\bank_out[6] [21]), .A2 (n_13), .B1
       (\bank_out[7] [21]), .B2 (n_15), .ZN (n_18));
  aoi22d1 g6530__4733(.A1 (\bank_out[6] [10]), .A2 (n_13), .B1
       (\bank_out[7] [10]), .B2 (n_15), .ZN (n_17));
  aoi22d1 g6531__6161(.A1 (\bank_out[2] [10]), .A2 (n_8), .B1
       (\bank_out[3] [10]), .B2 (n_12), .ZN (n_16));
  nd02d0 g6532__9315(.A1 (n_14), .A2 (n_2), .ZN (bank_we[1]));
  nd02d0 g6533__9945(.A1 (n_8), .A2 (n_2), .ZN (bank_we[2]));
  nd02d0 g6534__2883(.A1 (n_12), .A2 (n_2), .ZN (bank_we[3]));
  nd02d0 g6535__2346(.A1 (n_11), .A2 (n_2), .ZN (bank_we[0]));
  nd02d0 g6536__1666(.A1 (n_15), .A2 (n_2), .ZN (bank_we[7]));
  nd02d0 g6537__7410(.A1 (n_9), .A2 (n_2), .ZN (bank_we[5]));
  nd02d0 g6538__6417(.A1 (n_10), .A2 (n_2), .ZN (bank_we[4]));
  nd02d0 g6539__5477(.A1 (n_13), .A2 (n_2), .ZN (bank_we[6]));
  inv0d0 g6540(.I (n_15), .ZN (bank_select[7]));
  inv0d0 g6541(.I (n_14), .ZN (bank_select[1]));
  inv0d0 g6542(.I (n_13), .ZN (bank_select[6]));
  inv0d0 g6543(.I (n_12), .ZN (bank_select[3]));
  nr02d2 g6544__2398(.A1 (n_1), .A2 (n_3), .ZN (n_15));
  an02d2 g6545__5107(.A1 (n_7), .A2 (n_3), .Z (n_14));
  nr02d2 g6546__6260(.A1 (n_6), .A2 (n_3), .ZN (n_13));
  an02d2 g6547__4319(.A1 (n_7), .A2 (A[7]), .Z (n_12));
  inv0d0 g6548(.I (n_11), .ZN (n_145));
  inv0d0 g6549(.I (n_10), .ZN (bank_select[4]));
  inv0d0 g6550(.I (n_9), .ZN (bank_select[5]));
  inv0d0 g6551(.I (n_8), .ZN (bank_select[2]));
  an02d2 g6552__8428(.A1 (n_0), .A2 (n_3), .Z (n_11));
  nr02d2 g6553__5526(.A1 (n_6), .A2 (A[7]), .ZN (n_10));
  nr02d2 g6554__6783(.A1 (n_1), .A2 (A[7]), .ZN (n_9));
  an02d2 g6555__3680(.A1 (n_0), .A2 (A[7]), .Z (n_8));
  nr02d0 g6558__1617(.A1 (n_5), .A2 (A[8]), .ZN (n_7));
  nd02d0 g6559__2802(.A1 (n_4), .A2 (A[8]), .ZN (n_6));
  nd12d0 g6561__1705(.A1 (CEN), .A2 (A[6]), .ZN (n_5));
  nr02d0 g6563__5122(.A1 (CEN), .A2 (A[6]), .ZN (n_4));
  inv0d0 g6564(.I (A[7]), .ZN (n_3));
  inv0d0 g6565(.I (GWEN), .ZN (n_2));
  nd12d1 g2__8246(.A1 (n_5), .A2 (A[8]), .ZN (n_1));
  an12d1 g6566__7098(.A1 (A[8]), .A2 (n_4), .Z (n_0));
endmodule

