/* Generated by Tessent Shell 2022.4 at Mon Mar 10 14:55:16 IST 2025 */
module dff_14(clk, q, d, ts_sea0, ts_intno12);
  input  clk, d, ts_intno12, ts_sea0;
  output q;

  wire UNCONNECTED12;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno12), .Q(q), .QN(UNCONNECTED12)
  );
endmodule

module dff_15(clk, q, d, ts_sea0, ts_intno11);
  input  clk, d, ts_intno11, ts_sea0;
  output q;

  wire UNCONNECTED11;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno11), .Q(q), .QN(UNCONNECTED11)
  );
endmodule

module dff_16(clk, q, d, ts_sea0, ts_intno10);
  input  clk, d, ts_intno10, ts_sea0;
  output q;

  wire UNCONNECTED10;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno10), .Q(q), .QN(UNCONNECTED10)
  );
endmodule

module dff_17(clk, q, d, ts_sea0, ts_intno1);
  input  clk, d, ts_intno1, ts_sea0;
  output q;

  wire UNCONNECTED9;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno1), .Q(q), .QN(UNCONNECTED9)
  );
endmodule

module dff_18(clk, q, d, ts_sea0, ts_intno8, ts_no9);
  input  clk, d, ts_intno8, ts_sea0;
  output q, ts_no9;

  wire UNCONNECTED8;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno8), .Q(q), .QN(UNCONNECTED8)
  );
  active_high_latch ts_lockup_latchp_clkc1_intno9_i(
      .CLK(clk), .D(q), .Q(ts_no9)
  );
endmodule

module dff_19(clk, q, d, ts_sea0, ts_intno7);
  input  clk, d, ts_intno7, ts_sea0;
  output q;

  wire UNCONNECTED7;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno7), .Q(q), .QN(UNCONNECTED7)
  );
endmodule

module dff_20(clk, q, d, ts_sea0, ts_intno6);
  input  clk, d, ts_intno6, ts_sea0;
  output q;

  wire UNCONNECTED6;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno6), .Q(q), .QN(UNCONNECTED6)
  );
endmodule

module dff_21(clk, q, d, ts_sea0, ts_intno5);
  input  clk, d, ts_intno5, ts_sea0;
  output q;

  wire UNCONNECTED5;

  SDFF_X1 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno5), .Q(q), .QN(UNCONNECTED5)
  );
endmodule

module dff_22(clk, q, d, ts_sea0, ts_intno4);
  input  clk, d, ts_intno4, ts_sea0;
  output q;

  wire UNCONNECTED4;

  SDFF_X2 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno4), .Q(q), .QN(UNCONNECTED4)
  );
endmodule

module dff_23(clk, q, d, ts_sea0, ts_intno3);
  input  clk, d, ts_intno3, ts_sea0;
  output q;

  wire UNCONNECTED3;

  SDFF_X2 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno3), .Q(q), .QN(UNCONNECTED3)
  );
endmodule

module dff_24(clk, q, d, ts_sea0, ts_intno2);
  input  clk, d, ts_intno2, ts_sea0;
  output q;

  wire UNCONNECTED2;

  SDFF_X2 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno2), .Q(q), .QN(UNCONNECTED2)
  );
endmodule

module dff_25(clk, q, d, ts_sea0, ts_intno13);
  input  clk, d, ts_intno13, ts_sea0;
  output q;

  wire UNCONNECTED1;

  SDFF_X2 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno13), .Q(q), .QN(UNCONNECTED1)
  );
endmodule

module dff_26(clk, q, d, ts_sea0, ts_intno0);
  input  clk, d, ts_intno0, ts_sea0;
  output q;

  wire UNCONNECTED0;

  SDFF_X2 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_intno0), .Q(q), .QN(UNCONNECTED0)
  );
endmodule

module dff(clk, q, d, ts_sea0, ts_extsi14);
  input  clk, d, ts_extsi14, ts_sea0;
  output q;

  wire UNCONNECTED, ts_pbuf_extsi14_;

  SDFF_X2 q_reg(
      .CK(clk), .D(d), .SE(ts_sea0), .SI(ts_pbuf_extsi14_), .Q(q), .QN(UNCONNECTED)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi14_i(
      .A(ts_extsi14), .Z(ts_pbuf_extsi14_)
  );
endmodule

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67, ts_si, 
            ts_so, scan_en);
  input  [0:0] ts_si;
  input  GND, VDD, CK, G0, G1, G2, scan_en;
  output [0:0] ts_so;
  output G117, G118, G132, G133, G66, G67;

  wire G10, G11, G12, G13, G14, G15, G22, G23, G29, G30, G34, G39, G44, G56, 
       G86, G92, G98, G102, G107, G113, G119, G125, n_4, n_5, n_8, n_9, n_10, 
       n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22, 
       n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34, 
       n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46, 
       n_47, n_48, n_49, n_50, ts_no9;

  assign ts_so = ts_no9;
  dff DFF_0(
      CK, G10, G29, scan_en, ts_si
  );
  dff_26 DFF_1(
      CK, G11, G30, scan_en, G10
  );
  dff_25 DFF_2(
      CK, G12, G34, scan_en, G23
  );
  dff_24 DFF_3(
      CK, G13, G39, scan_en, G12
  );
  dff_23 DFF_4(
      CK, G14, G44, scan_en, G13
  );
  dff_22 DFF_5(
      CK, G15, G56, scan_en, G14
  );
  dff_21 DFF_6(
      CK, G66, G86, scan_en, G15
  );
  dff_20 DFF_7(
      CK, G67, G92, scan_en, G66
  );
  dff_19 DFF_8(
      CK, G117, G98, scan_en, G67
  );
  dff_18 DFF_9(
      CK, G118, G102, scan_en, G117, ts_no9
  );
  dff_17 DFF_10(
      CK, G132, G107, scan_en, G11
  );
  dff_16 DFF_11(
      CK, G133, G113, scan_en, G132
  );
  dff_15 DFF_12(
      CK, G22, G119, scan_en, G133
  );
  dff_14 DFF_13(
      CK, G23, G125, scan_en, G22
  );
  OAI21_X2 g1358__2398(
      .A(n_46), .B1(n_50), .B2(G10), .ZN(G107)
  );
  NOR2_X2 g1359__5107(
      .A1(n_50), .A2(G0), .ZN(G56)
  );
  NOR2_X2 g1360__6260(
      .A1(n_48), .A2(G0), .ZN(G44)
  );
  NAND2_X2 g1361__4319(
      .A1(n_47), .A2(n_49), .ZN(G102)
  );
  NOR2_X2 g1362__8428(
      .A1(n_45), .A2(G0), .ZN(G39)
  );
  OAI21_X2 g1363__5526(
      .A(n_47), .B1(n_32), .B2(n_11), .ZN(G86)
  );
  AOI21_X2 g1364__6783(
      .A(n_39), .B1(n_40), .B2(G15), .ZN(n_50)
  );
  OAI211_X2 g1365__3680(
      .A(n_44), .B(n_33), .C1(n_32), .C2(n_15), .ZN(G98)
  );
  OAI221_X2 g1366__1617(
      .A(n_44), .B1(n_32), .B2(n_13), .C1(n_33), .C2(G11), .ZN(G92)
  );
  AOI211_X2 g1367__2802(
      .A(n_43), .B(n_41), .C1(n_31), .C2(G118), .ZN(n_49)
  );
  XOR2_X2 g1368__1705(
      .A(n_42), .B(G14), .Z(n_48)
  );
  NOR2_X2 g1369__5122(
      .A1(n_37), .A2(G0), .ZN(G30)
  );
  NOR2_X2 g1370__8246(
      .A1(n_38), .A2(G0), .ZN(G34)
  );
  AND2_X2 g1371__7098(
      .A1(n_40), .A2(n_36), .ZN(n_47)
  );
  AOI21_X2 g1372__6131(
      .A(n_41), .B1(n_31), .B2(G132), .ZN(n_46)
  );
  OAI22_X2 g1373__1881(
      .A1(n_17), .A2(n_33), .B1(n_32), .B2(n_12), .ZN(G113)
  );
  AOI221_X2 g1374__5115(
      .A(n_34), .B1(n_18), .B2(n_21), .C1(n_28), .C2(G13), .ZN(n_45)
  );
  NOR2_X2 g1375__7482(
      .A1(n_29), .A2(G0), .ZN(G125)
  );
  NOR2_X2 g1376__4733(
      .A1(n_30), .A2(G0), .ZN(G119)
  );
  AOI21_X1 g1377__6161(
      .A(G10), .B1(n_25), .B2(n_14), .ZN(n_43)
  );
  AOI21_X2 g1378__9315(
      .A(G23), .B1(n_24), .B2(n_22), .ZN(n_42)
  );
  NAND2_X2 g1379__9945(
      .A1(n_35), .A2(G11), .ZN(n_44)
  );
  NOR3_X2 g1380__2883(
      .A1(n_23), .A2(n_27), .A3(G14), .ZN(n_39)
  );
  XNOR2_X2 g1381__2346(
      .A(n_18), .B(G12), .ZN(n_38)
  );
  AOI22_X2 g1382__1666(
      .A1(n_24), .A2(n_23), .B1(G11), .B2(n_8), .ZN(n_37)
  );
  OAI211_X2 g1383__7410(
      .A(n_26), .B(n_14), .C1(n_27), .C2(G12), .ZN(n_36)
  );
  AND3_X2 g1384__6417(
      .A1(n_35), .A2(n_10), .A3(G14), .ZN(n_41)
  );
  NAND2_X2 g1385__5477(
      .A1(n_34), .A2(n_16), .ZN(n_40)
  );
  NOR2_X2 g1386__2398(
      .A1(n_19), .A2(G12), .ZN(n_35)
  );
  NOR2_X2 g1387__5107(
      .A1(n_23), .A2(n_10), .ZN(n_34)
  );
  NAND2_X2 g1388__6260(
      .A1(n_20), .A2(n_4), .ZN(n_33)
  );
  INV_X4 g1389(
      .A(n_32), .ZN(n_31)
  );
  XNOR2_X2 g1390__4319(
      .A(G2), .B(G22), .ZN(n_30)
  );
  XNOR2_X2 g1391__8428(
      .A(G1), .B(G23), .ZN(n_29)
  );
  OAI21_X2 g1392__5526(
      .A(G10), .B1(G11), .B2(n_5), .ZN(n_28)
  );
  OAI211_X2 g1393__6783(
      .A(n_14), .B(G14), .C1(G12), .C2(G13), .ZN(n_32)
  );
  INV_X1 g1394(
      .A(n_25), .ZN(n_26)
  );
  INV_X1 g1395(
      .A(n_23), .ZN(n_22)
  );
  NOR2_X1 g1396__3680(
      .A1(n_5), .A2(G13), .ZN(n_21)
  );
  NAND2_X2 g1397__1617(
      .A1(n_10), .A2(G22), .ZN(n_27)
  );
  NAND2_X2 g1398__2802(
      .A1(n_4), .A2(G13), .ZN(n_25)
  );
  NOR2_X2 g1399__1705(
      .A1(G11), .A2(n_8), .ZN(n_24)
  );
  NAND2_X2 g1400__5122(
      .A1(n_5), .A2(G13), .ZN(n_23)
  );
  INV_X1 g1401(
      .A(n_19), .ZN(n_20)
  );
  NAND2_X2 g1402__8246(
      .A1(G11), .A2(G12), .ZN(n_17)
  );
  NOR2_X2 g1403__7098(
      .A1(G0), .A2(G10), .ZN(G29)
  );
  NOR2_X2 g1404__6131(
      .A1(G14), .A2(G22), .ZN(n_16)
  );
  NAND2_X2 g1405__1881(
      .A1(n_14), .A2(n_9), .ZN(n_19)
  );
  NOR2_X2 g1406__5115(
      .A1(n_8), .A2(n_10), .ZN(n_18)
  );
  INV_X2 g1407(
      .A(G117), .ZN(n_15)
  );
  INV_X4 g1408(
      .A(G15), .ZN(n_14)
  );
  INV_X2 g1415(
      .A(G10), .ZN(n_8)
  );
  INV_X4 g1420(
      .A(G12), .ZN(n_5)
  );
  INV_X4 g1421(
      .A(G67), .ZN(n_13)
  );
  INV_X4 g1422(
      .A(G133), .ZN(n_12)
  );
  INV_X2 g1423(
      .A(G66), .ZN(n_11)
  );
  INV_X4 g1425(
      .A(G11), .ZN(n_10)
  );
  INV_X2 drc_bufs1427(
      .A(G14), .ZN(n_4)
  );
  INV_X2 drc_bufs1439(
      .A(G13), .ZN(n_9)
  );
endmodule

