
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  7 2025 16:24:17 IST (Mar  7 2025 10:54:17 UTC)

// Verification Directory fv/s298 

module dff(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_26(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX2 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_25(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX2 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_24(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX2 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_23(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_22(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_21(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_20(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_19(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_18(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_17(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_16(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_15(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module dff_14(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1 q_reg(.CK (clk), .D (d), .Q (q));
endmodule

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67);
  input GND, VDD, CK, G0, G1, G2;
  output G117, G118, G132, G133, G66, G67;
  wire GND, VDD, CK, G0, G1, G2;
  wire G117, G118, G132, G133, G66, G67;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire G29, G30, G34, G39, G44, G56, G86, G92;
  wire G98, G102, G107, G113, G119, G125, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40;
  dff DFF_0(CK, G10, G29);
  dff_26 DFF_1(CK, G11, G30);
  dff_25 DFF_2(CK, G12, G34);
  dff_24 DFF_3(CK, G13, G39);
  dff_23 DFF_4(CK, G14, G44);
  dff_22 DFF_5(CK, G15, G56);
  dff_21 DFF_6(CK, G66, G86);
  dff_20 DFF_7(CK, G67, G92);
  dff_19 DFF_8(CK, G117, G98);
  dff_18 DFF_9(CK, G118, G102);
  dff_17 DFF_10(CK, G132, G107);
  dff_16 DFF_11(CK, G133, G113);
  dff_15 DFF_12(CK, G22, G119);
  dff_14 DFF_13(CK, G23, G125);
  OAI21XL g1198__2398(.A0 (n_39), .A1 (G10), .B0 (n_36), .Y (G107));
  NOR2X1 g1199__5107(.A (n_39), .B (G0), .Y (G56));
  NOR2X1 g1200__6260(.A (G0), .B (n_38), .Y (G44));
  NAND2X1 g1201__4319(.A (n_40), .B (n_37), .Y (G102));
  AOI21X1 g1202__8428(.A0 (n_35), .A1 (n_25), .B0 (G0), .Y (G39));
  AOI211X1 g1203__5526(.A0 (n_19), .A1 (G118), .B0 (n_31), .C0 (n_33),
       .Y (n_40));
  OAI221XL g1204__6783(.A0 (n_20), .A1 (n_6), .B0 (n_21), .B1 (G11),
       .C0 (n_34), .Y (G92));
  OAI2BB1X1 g1205__3680(.A0N (G66), .A1N (n_19), .B0 (n_37), .Y (G86));
  OAI211X1 g1206__1617(.A0 (n_20), .A1 (n_9), .B0 (n_34), .C0 (n_21),
       .Y (G98));
  XOR2X1 g1207__2802(.A (n_32), .B (G14), .Y (n_38));
  AOI32X1 g1208__1705(.A0 (n_12), .A1 (n_13), .A2 (n_2), .B0 (n_30),
       .B1 (G15), .Y (n_39));
  NOR2X1 g1209__5122(.A (G0), .B (n_29), .Y (G30));
  NOR2X1 g1210__8246(.A (G0), .B (n_26), .Y (G34));
  AND2X2 g1211__7098(.A (n_30), .B (n_28), .Y (n_37));
  AOI21X1 g1212__6131(.A0 (n_19), .A1 (G132), .B0 (n_31), .Y (n_36));
  OAI2BB1X1 g1213__1881(.A0N (G133), .A1N (n_19), .B0 (n_27), .Y
       (G113));
  AOI32X1 g1214__5115(.A0 (n_10), .A1 (n_4), .A2 (G12), .B0 (n_17), .B1
       (G13), .Y (n_35));
  NOR2X1 g1215__7482(.A (n_16), .B (G0), .Y (G119));
  AOI21X1 g1216__4733(.A0 (n_11), .A1 (n_5), .B0 (G10), .Y (n_33));
  NOR2X1 g1217__6161(.A (n_18), .B (G0), .Y (G125));
  AOI21X1 g1218__9315(.A0 (n_14), .A1 (n_13), .B0 (G23), .Y (n_32));
  NAND2X1 g1219__9945(.A (n_24), .B (G11), .Y (n_34));
  AOI21X1 g1220__2883(.A0 (n_3), .A1 (G11), .B0 (n_22), .Y (n_29));
  NAND3BX1 g1221__2346(.AN (n_11), .B (n_23), .C (n_5), .Y (n_28));
  NAND3BX1 g1222__1666(.AN (n_21), .B (G11), .C (G12), .Y (n_27));
  XNOR2X1 g1223__7410(.A (n_10), .B (G12), .Y (n_26));
  AND3X2 g1224__6417(.A (n_24), .B (n_7), .C (G14), .Y (n_31));
  OR3XL g1225__5477(.A (n_25), .B (G14), .C (G22), .Y (n_30));
  NAND2BX1 g1226__2398(.AN (G12), .B (n_12), .Y (n_23));
  NOR2BXL g1227__5107(.AN (n_14), .B (n_13), .Y (n_22));
  NAND2X1 g1228__6260(.A (n_13), .B (G11), .Y (n_25));
  NOR2X1 g1229__4319(.A (n_15), .B (G15), .Y (n_24));
  INVX1 g1230(.A (n_20), .Y (n_19));
  XNOR2X1 g1231__8428(.A (G1), .B (G23), .Y (n_18));
  OAI21XL g1232__5526(.A0 (n_8), .A1 (G11), .B0 (G10), .Y (n_17));
  XNOR2X1 g1233__6783(.A (G2), .B (G22), .Y (n_16));
  NAND3X1 g1234__3680(.A (n_5), .B (n_2), .C (n_4), .Y (n_21));
  NAND3X1 g1235__1617(.A (n_15), .B (n_5), .C (G14), .Y (n_20));
  NAND2X1 g1236__2802(.A (n_8), .B (n_4), .Y (n_15));
  NOR2X1 g1237__1705(.A (n_3), .B (G11), .Y (n_14));
  AND2X2 g1238__5122(.A (n_8), .B (G13), .Y (n_13));
  NOR2X1 g1239__8246(.A (G0), .B (G10), .Y (G29));
  AND2X2 g1240__7098(.A (n_7), .B (G22), .Y (n_12));
  NAND2X1 g1241__6131(.A (n_2), .B (G13), .Y (n_11));
  AND2X2 g1242__1881(.A (G11), .B (G10), .Y (n_10));
  INVX1 g1243(.A (G117), .Y (n_9));
  CLKINVX3 g1244(.A (G12), .Y (n_8));
  INVX1 g1245(.A (G11), .Y (n_7));
  INVX1 g1246(.A (G67), .Y (n_6));
  INVX1 g1247(.A (G15), .Y (n_5));
  INVX1 g1248(.A (G13), .Y (n_4));
  INVX1 g1249(.A (G10), .Y (n_3));
  INVX1 g1250(.A (G14), .Y (n_2));
endmodule

