/* Generated by Tessent Shell 2022.4 at Mon Apr 28 14:29:32 IST 2025 */
module memlibc_memory_bist_assembly(BIST_CLK, m1_A, m1_WEB, m1_CSB, m1_I, m1_O, 
                                    ijtag_tck, ijtag_reset, ijtag_ce, ijtag_se, 
                                    ijtag_ue, ijtag_sel, ijtag_si, ijtag_so);
  input  [7:0] m1_I;
  input  [4:0] m1_A;
  input  BIST_CLK, m1_WEB, m1_CSB;
  output [7:0] m1_O;
  input ijtag_tck, ijtag_reset, ijtag_ce, ijtag_se, ijtag_ue, ijtag_sel, 
        ijtag_si;
  wire ijtag_tck, ijtag_reset, ijtag_ce, ijtag_se, ijtag_ue, ijtag_sel, 
       ijtag_si;
  output ijtag_so;
  wire ijtag_so;


  
  wire [2:0] BIST_SETUP;
  wire memlibc_memory_bist_assembly_rtl_tessent_sib_mbist_inst_so, 
       memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_so, 
       memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_to_select, 
       ijtag_to_tck, ijtag_to_ue, ijtag_to_reset, ijtag_to_se, ijtag_to_ce, 
       ijtag_to_sel, ltest_to_en, ltest_to_mem_bypass_en, ltest_to_scan_en, 
       ltest_to_mcp_bounding_en, BIST_HOLD, BIST_SELECT_TEST_DATA, 
       to_controllers_tck, mcp_bounding_to_en, scan_to_en, memory_bypass_to_en, 
       ltest_to_en_ts1, BIST_ALGO_MODE0, BIST_ALGO_MODE1, ENABLE_MEM_RESET, 
       REDUCED_ADDRESS_COUNT, BIST_ASYNC_RESET, MBISTPG_SO, MBISTPG_DONE, 
       MBISTPG_GO, BIST_DIAG_EN, FL_CNT_MODE0, FL_CNT_MODE1, 
       INCLUDE_MEM_RESULTS_REG, to_interfaces_tck, 
       memlibc_memory_bist_assembly_rtl_tessent_mbist_bap_inst_so;
  wire [0:0] toBist, bistEn;
  memlibc_memory_bist_assembly_mem_container mem_container_inst(
      .m1_A(m1_A), .BIST_CLK(BIST_CLK), .m1_WEB(m1_WEB), .m1_CSB(m1_CSB), .m1_I(m1_I), 
      .m1_mem_inst_O(m1_O), .BIST_HOLD(BIST_HOLD), .BIST_SETUP(BIST_SETUP[0]), 
                        .BIST_SETUP_ts1(BIST_SETUP[1]), .BIST_SETUP_ts2(BIST_SETUP[2]), 
                        .BIST_SELECT_TEST_DATA(BIST_SELECT_TEST_DATA), 
                        .to_controllers_tck(to_controllers_tck), 
                        .mcp_bounding_to_en(mcp_bounding_to_en), .scan_to_en(scan_to_en), 
                        .memory_bypass_to_en(memory_bypass_to_en), 
                        .ltest_to_en(ltest_to_en_ts1), .BIST_ALGO_MODE0({
                        BIST_ALGO_MODE1, BIST_ALGO_MODE0}), .ENABLE_MEM_RESET(ENABLE_MEM_RESET), 
                        .REDUCED_ADDRESS_COUNT(REDUCED_ADDRESS_COUNT), 
                        .BIST_ASYNC_RESET(BIST_ASYNC_RESET), .toBist(toBist), 
                        .MBISTPG_SO(MBISTPG_SO), .bistEn(bistEn), 
                        .MBISTPG_DONE(MBISTPG_DONE), .MBISTPG_GO(MBISTPG_GO), 
                        .BIST_DIAG_EN(BIST_DIAG_EN), .FL_CNT_MODE0({
                        FL_CNT_MODE1, FL_CNT_MODE0}), 
                        .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
                        .to_interfaces_tck(to_interfaces_tck)
  );

  memlibc_memory_bist_assembly_rtl_tessent_sib_1 memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst(
      .ijtag_reset(ijtag_reset), .ijtag_sel(ijtag_sel), .ijtag_si(ijtag_si), .ijtag_ce(ijtag_ce), 
      .ijtag_se(ijtag_se), .ijtag_ue(ijtag_ue), .ijtag_tck(ijtag_tck), .ijtag_so(ijtag_so), 
      .ijtag_from_so(memlibc_memory_bist_assembly_rtl_tessent_sib_mbist_inst_so), 
      .ltest_si(1'b0), .ltest_scan_en(1'b0), .ltest_en(1'b0), .ltest_clk(1'b0), 
      .ltest_mem_bypass_en(1'b1), .ltest_mcp_bounding_en(1'b0), .ltest_occ_en(1'b0), 
      .ltest_async_set_reset_static_disable(1'b0), .ltest_static_clock_control_mode(1'b0), 
      .ltest_clock_sequence({1'b0, 1'b0}), .ijtag_to_tck(ijtag_to_tck), .ijtag_to_reset(ijtag_to_reset), 
      .ijtag_to_si(memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_so), .ijtag_to_ce(ijtag_to_ce), 
      .ijtag_to_se(ijtag_to_se), .ijtag_to_ue(ijtag_to_ue), .ltest_so(), .ltest_to_en(ltest_to_en), 
      .ltest_to_mem_bypass_en(ltest_to_mem_bypass_en), .ltest_to_mcp_bounding_en(ltest_to_mcp_bounding_en), 
      .ltest_to_scan_en(ltest_to_scan_en), .ijtag_to_sel(memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_to_select)
  );

  memlibc_memory_bist_assembly_rtl_tessent_sib_2 memlibc_memory_bist_assembly_rtl_tessent_sib_mbist_inst(
      .ijtag_reset(ijtag_to_reset), .ijtag_sel(memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_to_select), 
      .ijtag_si(memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_so), .ijtag_ce(ijtag_to_ce), 
      .ijtag_se(ijtag_to_se), .ijtag_ue(ijtag_to_ue), .ijtag_tck(ijtag_to_tck), 
      .ijtag_so(memlibc_memory_bist_assembly_rtl_tessent_sib_mbist_inst_so), .ijtag_from_so(memlibc_memory_bist_assembly_rtl_tessent_mbist_bap_inst_so), 
      .ijtag_to_sel(ijtag_to_sel)
  );

  memlibc_memory_bist_assembly_rtl_tessent_mbist_bap memlibc_memory_bist_assembly_rtl_tessent_mbist_bap_inst(
      .reset(ijtag_to_reset), .ijtag_select(ijtag_to_sel), .si(memlibc_memory_bist_assembly_rtl_tessent_sib_sti_inst_so), 
      .capture_en(ijtag_to_ce), .shift_en(ijtag_to_se), .shift_en_R(), .update_en(ijtag_to_ue), 
      .tck(ijtag_to_tck), .to_interfaces_tck(to_interfaces_tck), .to_controllers_tck(to_controllers_tck), 
      .mcp_bounding_en(ltest_to_mcp_bounding_en), .mcp_bounding_to_en(mcp_bounding_to_en), 
      .scan_en(ltest_to_scan_en), .scan_to_en(scan_to_en), .memory_bypass_en(ltest_to_mem_bypass_en), 
      .memory_bypass_to_en(memory_bypass_to_en), .ltest_en(ltest_to_en), .ltest_to_en(ltest_to_en_ts1), 
      .BIST_HOLD(BIST_HOLD), .ENABLE_MEM_RESET(ENABLE_MEM_RESET), .REDUCED_ADDRESS_COUNT(REDUCED_ADDRESS_COUNT), 
      .BIST_SELECT_TEST_DATA(BIST_SELECT_TEST_DATA), .BIST_ALGO_MODE0(BIST_ALGO_MODE0), 
      .BIST_ALGO_MODE1(BIST_ALGO_MODE1), .BIST_DIAG_EN(BIST_DIAG_EN), .BIST_ASYNC_RESET(BIST_ASYNC_RESET), 
      .FL_CNT_MODE0(FL_CNT_MODE0), .FL_CNT_MODE1(FL_CNT_MODE1), .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
      .CHAIN_BYPASS_EN(), .TCK_MODE(), .BIST_SETUP(BIST_SETUP[2:0]), .MBISTPG_GO(MBISTPG_GO), 
      .MBISTPG_DONE(MBISTPG_DONE), .bistEn(bistEn), .toBist(toBist), .fromBist(MBISTPG_SO), 
      .so(memlibc_memory_bist_assembly_rtl_tessent_mbist_bap_inst_so)
  );
endmodule

module memlibc_memory_bist_assembly_mem_container(m1_A, BIST_CLK, m1_WEB, m1_CSB, 
                                                  m1_I, m1_mem_inst_O, 
                        BIST_HOLD, BIST_SETUP, BIST_SETUP_ts1, BIST_SETUP_ts2, 
                        BIST_SELECT_TEST_DATA, to_controllers_tck, 
                        mcp_bounding_to_en, scan_to_en, memory_bypass_to_en, 
                        ltest_to_en, BIST_ALGO_MODE0, ENABLE_MEM_RESET, 
                        REDUCED_ADDRESS_COUNT, BIST_ASYNC_RESET, toBist, 
                        MBISTPG_SO, bistEn, MBISTPG_DONE, MBISTPG_GO, 
                        BIST_DIAG_EN, FL_CNT_MODE0, INCLUDE_MEM_RESULTS_REG, 
                        to_interfaces_tck);
  input  [7:0] m1_I;
  input  [4:0] m1_A;
  input  BIST_CLK, m1_WEB, m1_CSB;
  output [7:0] m1_mem_inst_O;
  input BIST_HOLD, BIST_SETUP, BIST_SETUP_ts2, BIST_SELECT_TEST_DATA, 
        to_controllers_tck, mcp_bounding_to_en, scan_to_en, 
        memory_bypass_to_en, ltest_to_en, ENABLE_MEM_RESET, 
        REDUCED_ADDRESS_COUNT, BIST_ASYNC_RESET, toBist, bistEn, BIST_DIAG_EN, 
        INCLUDE_MEM_RESULTS_REG, to_interfaces_tck;
  wire BIST_HOLD, BIST_SETUP, BIST_SETUP_ts2, BIST_SELECT_TEST_DATA, 
       to_controllers_tck, mcp_bounding_to_en, scan_to_en, memory_bypass_to_en, 
       ltest_to_en, ENABLE_MEM_RESET, REDUCED_ADDRESS_COUNT, BIST_ASYNC_RESET, 
       toBist, bistEn, BIST_DIAG_EN, INCLUDE_MEM_RESULTS_REG, 
       to_interfaces_tck;
  output MBISTPG_SO, MBISTPG_DONE, MBISTPG_GO;
  wire MBISTPG_SO, MBISTPG_DONE, MBISTPG_GO;
  input [1:1] BIST_SETUP_ts1;
  wire [1:1] BIST_SETUP_ts1;
  input [1:0] BIST_ALGO_MODE0, FL_CNT_MODE0;
  wire [1:0] BIST_ALGO_MODE0, FL_CNT_MODE0;


  
  wire [1:0] BIST_COL_ADD;
  wire [2:0] BIST_ROW_ADD;
  wire [1:0] BIST_WRITE_DATA, BIST_EXPECT_DATA;
  wire [4:0] m1_mem_inst_interface_inst_A;
  wire MEM0_BIST_COLLAR_SI, BIST_SO, BIST_GO, BIST_COLLAR_DIAG_EN, 
       BIST_WRITEENABLE, BIST_OUTPUTENABLE, BIST_SELECT, BIST_CMP, 
       BIST_COLLAR_EN0, BIST_RUN_TO_COLLAR0, BIST_TESTDATA_SELECT_TO_COLLAR, 
       BIST_ON_TO_COLLAR, BIST_SHIFT_COLLAR, BIST_COLLAR_SETUP, 
       BIST_CLEAR_DEFAULT, BIST_CLEAR, BIST_COLLAR_HOLD, FREEZE_STOP_ERROR, 
       ERROR_CNT_ZERO, MBISTPG_RESET_REG_SETUP2, WEB, CSB;
  wire [7:0] m1_mem_inst_interface_inst_I;
  SPRAM_32x8 m1_mem_inst(
      .A(m1_mem_inst_interface_inst_A), .CE(BIST_CLK), .WEB(WEB), .OEB(1'b0), .CSB(CSB), .I(m1_mem_inst_interface_inst_I), 
      .O(m1_mem_inst_O)
  );

  memlibc_memory_bist_assembly_rtl_tessent_mbist_c1_controller memlibc_memory_bist_assembly_rtl_tessent_mbist_c1_controller_inst(
      .MBISTPG_ALGO_MODE(BIST_ALGO_MODE0[1:0]), .MBISTPG_MEM_RST(ENABLE_MEM_RESET), 
      .MBISTPG_REDUCED_ADDR_CNT_EN(REDUCED_ADDRESS_COUNT), .MEM_BYPASS_EN(memory_bypass_to_en), 
      .MCP_BOUNDING_EN(mcp_bounding_to_en), .MEM0_BIST_COLLAR_SO(BIST_SO), .FL_CNT_MODE(FL_CNT_MODE0[1:0]), 
      .BIST_COLLAR_GO(BIST_GO), .MBISTPG_DIAG_EN(BIST_DIAG_EN), .BIST_CLK(BIST_CLK), 
      .BIST_SI(toBist), .BIST_HOLD(BIST_HOLD), .BIST_SETUP2(BIST_SETUP_ts2), .BIST_SETUP({
      BIST_SETUP_ts1, BIST_SETUP}), .MBISTPG_TESTDATA_SELECT(BIST_SELECT_TEST_DATA), 
      .TCK(to_controllers_tck), .MBISTPG_EN(bistEn), .MBISTPG_ASYNC_RESETN(BIST_ASYNC_RESET), 
      .LV_TM(ltest_to_en), .MBISTPG_RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
      .BIST_COL_ADD(BIST_COL_ADD), .BIST_ROW_ADD(BIST_ROW_ADD), .BIST_WRITE_DATA(BIST_WRITE_DATA), 
      .BIST_EXPECT_DATA(BIST_EXPECT_DATA), .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), 
      .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), .MEM0_BIST_COLLAR_SI(MEM0_BIST_COLLAR_SI), 
      .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), 
      .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), .ERROR_CNT_ZERO(ERROR_CNT_ZERO), .BIST_COLLAR_DIAG_EN(BIST_COLLAR_DIAG_EN), 
      .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), .MBISTPG_SO(MBISTPG_SO), 
      .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_OUTPUTENABLE(BIST_OUTPUTENABLE), 
      .BIST_SELECT(BIST_SELECT), .BIST_CMP(BIST_CMP), .BIST_COLLAR_EN0(BIST_COLLAR_EN0), 
      .BIST_RUN_TO_COLLAR0(BIST_RUN_TO_COLLAR0), .MBISTPG_GO(MBISTPG_GO), .MBISTPG_DONE(MBISTPG_DONE), 
      .BIST_ON_TO_COLLAR(BIST_ON_TO_COLLAR)
  );

  memlibc_memory_bist_assembly_rtl_tessent_mbist_c1_interface_m1 m1_mem_inst_interface_inst(
      .WEB_IN(m1_WEB), .CSB_IN(m1_CSB), .A_IN(m1_A[4:0]), .I_IN(m1_I[7:0]), .O(m1_mem_inst_O), 
      .TCK(to_interfaces_tck), .BIST_CMP(BIST_CMP), .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
      .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_OUTPUTENABLE(BIST_OUTPUTENABLE), 
      .BIST_SELECT(BIST_SELECT), .BIST_COL_ADD(BIST_COL_ADD), .BIST_ROW_ADD(BIST_ROW_ADD), 
      .BIST_WRITE_DATA(BIST_WRITE_DATA), .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
      .MEM_BYPASS_EN(memory_bypass_to_en), .SCAN_SHIFT_EN(scan_to_en), .MCP_BOUNDING_EN(mcp_bounding_to_en), 
      .BIST_ON(BIST_ON_TO_COLLAR), .BIST_RUN(BIST_RUN_TO_COLLAR0), .BIST_ASYNC_RESETN(BIST_ASYNC_RESET), 
      .BIST_CLK(BIST_CLK), .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), .BIST_EXPECT_DATA(BIST_EXPECT_DATA), 
      .BIST_SI(MEM0_BIST_COLLAR_SI), .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), 
      .BIST_DIAG_EN(BIST_COLLAR_DIAG_EN), .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), 
      .BIST_CLEAR(BIST_CLEAR), .BIST_SETUP0(BIST_SETUP), .LV_TM(ltest_to_en), .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), 
      .BIST_COLLAR_EN(BIST_COLLAR_EN0), .RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
      .ERROR_CNT_ZERO(ERROR_CNT_ZERO), .WEB(WEB), .CSB(CSB), .A(m1_mem_inst_interface_inst_A), 
      .I(m1_mem_inst_interface_inst_I), .SCAN_OBS_FLOPS(), .BIST_SO(BIST_SO), .BIST_GO(BIST_GO)
  );
endmodule

